use super::*;

pub const DEFAULT_HOMEBREW_PYTHON_FORMULA: &str = "python@3";

pub fn release_formula(
    repo: &RepoRuntime,
    release_id: &str,
    name: &str,
) -> Result<JsonValue, String> {
    release_formula_with_python(repo, release_id, name, DEFAULT_HOMEBREW_PYTHON_FORMULA)
}

pub fn release_formula_with_python(
    repo: &RepoRuntime,
    release_id: &str,
    name: &str,
    python_formula: &str,
) -> Result<JsonValue, String> {
    let python_formula = require_homebrew_formula_name(python_formula)?;
    let record = get_release_candidate(repo, release_id)?;
    let artifacts = record
        .get("artifacts")
        .and_then(JsonValue::as_array)
        .cloned()
        .unwrap_or_default();
    let wheel = artifacts
        .iter()
        .find(|row| string_field(row, "kind").as_deref() == Some("wheel"))
        .cloned()
        .ok_or_else(|| {
            format!("Release {release_id} does not have a wheel artifact yet. Run `ait release build {release_id}` first.")
        })?;
    let package = record
        .get("package")
        .and_then(JsonValue::as_object)
        .cloned()
        .unwrap_or_default();
    let scripts = package
        .get("scripts")
        .and_then(JsonValue::as_object)
        .cloned()
        .unwrap_or_default();
    let script_names = scripts.keys().cloned().collect::<Vec<_>>();
    let formula_path = repo
        .workspace_root()
        .join("dist")
        .join(format!("{name}.rb"));
    fs::create_dir_all(formula_path.parent().unwrap()).map_err(io_error)?;
    let homepage = package_homepage(&package, &required_string_field(&record, "repo_name")?);
    let license_literal = homebrew_license_literal(
        package
            .get("license")
            .and_then(JsonValue::as_str)
            .unwrap_or_default(),
    );
    let wheel_filename = artifact_download_name(&wheel)?;
    let mut symlink_lines = script_names
        .iter()
        .map(|script| format!("    bin.install_symlink libexec/\"bin/{script}\""))
        .collect::<Vec<_>>()
        .join("\n");
    if symlink_lines.is_empty() {
        symlink_lines =
            "    odie \"Formula generated without any console scripts to link.\"".to_string();
    }
    let formula_text = format!(
        "class {} < Formula\n  preserve_rpath\n\n  desc {}\n  homepage {}\n  url {}\n  sha256 {}\n  license {}\n\n  depends_on \"{}\"\n\n  def install\n    system Formula[\"{}\"].opt_bin/\"python3\", \"-m\", \"venv\", libexec\n    wheel = buildpath/{}\n    cp cached_download, wheel\n    system libexec/\"bin/python\", \"-m\", \"pip\", \"install\", wheel\n{}\n  end\n\n  def caveats\n    <<~EOS\n      Homebrew tap formula generated by `ait release formula`.\n      Expected console scripts from this package: {}.\n      This draft intentionally avoids auto-starting services.\n      `ait-server` still requires self-hosted runtime configuration.\n    EOS\n  end\nend\n",
        formula_class_name(name),
        json_quote(package.get("description").and_then(JsonValue::as_str).unwrap_or("ait release candidate")),
        json_quote(&homepage),
        json_quote(&required_string_field(&wheel, "url")?),
        json_quote(&required_string_field(&wheel, "sha256")?),
        license_literal,
        python_formula,
        python_formula,
        json_quote(&wheel_filename),
        symlink_lines,
        if script_names.is_empty() { "none".to_string() } else { script_names.join(", ") },
    );
    fs::write(&formula_path, formula_text).map_err(io_error)?;
    let mut updated_artifacts = artifacts;
    updated_artifacts.retain(|row| string_field(row, "kind").as_deref() != Some("formula"));
    updated_artifacts.push(artifact_info(repo, &formula_path)?);
    updated_artifacts.sort_by_key(|row| required_string_field(row, "kind").unwrap_or_default());
    let formula = json!({
        "name": name,
        "class_name": formula_class_name(name),
        "path": relative_or_absolute(repo, &formula_path),
        "artifact_kind": "wheel",
        "homepage": homepage,
        "license": package.get("license").cloned().unwrap_or(JsonValue::String(String::new())),
        "url": wheel.get("url").cloned().unwrap_or(JsonValue::Null),
        "sha256": wheel.get("sha256").cloned().unwrap_or(JsonValue::Null),
        "wheel_filename": wheel_filename,
    });
    let mut metadata = record
        .get("metadata")
        .and_then(JsonValue::as_object)
        .cloned()
        .unwrap_or_default();
    metadata.insert("formula".to_string(), formula.clone());
    update_release(
        repo,
        release_id,
        None,
        None,
        Some(JsonValue::Array(updated_artifacts)),
        Some(formula),
        Some(JsonValue::Object(metadata)),
    )?;
    get_release_candidate(repo, release_id)
}

fn require_homebrew_formula_name(value: &str) -> Result<&str, String> {
    if value.is_empty()
        || value.trim() != value
        || value.len() > 128
        || !value.chars().all(|character| {
            character.is_ascii_alphanumeric() || matches!(character, '@' | '+' | '-' | '.' | '_')
        })
    {
        return Err(
            "--python-formula must be a bounded Homebrew formula name without whitespace or path separators."
                .to_string(),
        );
    }
    Ok(value)
}

impl ReleaseProfile {
    pub(super) fn to_json(&self) -> JsonValue {
        json!({
            "required_scripts": self.required_scripts,
            "forbidden_scripts": self.forbidden_scripts,
            "release_docs": self.release_docs,
            "license_files": self.license_files,
            "contributor_files": self.contributor_files,
            "quickstart_files": self.quickstart_files,
            "excluded_paths": self.excluded_paths,
            "setuptools_package_excludes": self.setuptools_package_excludes,
        })
    }

    pub(super) fn requires_package_metadata(&self) -> bool {
        !self.license.is_empty()
            || !self.keywords.is_empty()
            || !self.classifiers.is_empty()
            || !self.required_package_urls.is_empty()
            || self.readme_file.is_some()
    }
}

impl PackageMetadata {
    pub(super) fn to_json(&self) -> JsonValue {
        json!({
            "name": self.name,
            "version": self.version,
            "description": self.description,
            "readme": self.readme,
            "requires_python": self.requires_python,
            "license": self.license,
            "license_files": self.license_files,
            "dependencies": self.dependencies,
            "scripts": self.scripts,
            "urls": self.urls,
            "classifiers": self.classifiers,
            "keywords": self.keywords,
        })
    }
}

pub(super) fn require_profile(profile: &str) -> Result<ReleaseProfile, String> {
    match profile.trim().to_ascii_lowercase().as_str() {
        "local-cli" => Ok(ReleaseProfile {
            id: "local-cli",
            required_scripts: &["ait", "ait-agent", "ait-agent-worker", "aitk"],
            forbidden_scripts: &["ait-server", "ait-worker", "ait-web"],
            release_docs: &[
                "README.md",
                "release/guides/LOCAL_QUICKSTART.md",
                "release/guides/PACKAGE_TARGETS.md",
                "release/guides/FUTURE_REPOSITORY_PREP.md",
                "release/guides/FUTURE_REPOSITORY_SPLIT_DRY_RUN.md",
                PUBLIC_PACKAGE_TARGETS_CONTRACT_PATH,
                PUBLIC_FUTURE_REPO_PREP_CONTRACT_PATH,
                PUBLIC_FUTURE_REPO_SPLIT_DRY_RUN_CONTRACT_PATH,
                "release/guides/COMPATIBILITY_MATRIX.md",
                "docs/legal/public_release_license_summary.md",
            ],
            license_files: &["LICENSE", "NOTICE", "docs/THIRD_PARTY_NOTICES.md"],
            contributor_files: &["docs/CONTRIBUTING.md"],
            quickstart_files: &["release/guides/LOCAL_QUICKSTART.md"],
            excluded_paths: &[
                "src/ait_server/**",
                "src/ait_web/**",
                "src/ait_native/server*.py",
                "src/ait_native/worker.py",
                "src/ait_native/web.py",
                "tests/ait_web/**",
            ],
            setuptools_package_excludes: &["ait_server*", "ait_web*"],
            description:
                "Agent-first Markdown workflow CLI with Apache-only local and companion surfaces",
            license: "Apache-2.0",
            readme_file: None,
            keywords: &["ai", "agent", "workflow", "markdown", "cli"],
            classifiers: &[
                "Development Status :: 3 - Alpha",
                "Environment :: Console",
                "Intended Audience :: Developers",
                "Operating System :: OS Independent",
                "Programming Language :: Python :: 3",
                "Programming Language :: Python :: 3.11",
                "Topic :: Software Development :: Build Tools",
                "Topic :: Software Development :: Version Control",
            ],
            required_package_urls: &["Homepage", "Documentation", "Source", "Issues", "Releases"],
            publish_support: false,
        }),
        other => Err(format!(
            "Unsupported release profile {other:?}. Supported profile: local-cli. Combined public packages use the separately licensed family release path."
        )),
    }
}

pub(super) fn shape_pyproject(text: &str, profile: &ReleaseProfile) -> Result<String, String> {
    let mut data = text.parse::<toml::Value>().map_err(|err| err.to_string())?;
    let root = data
        .as_table_mut()
        .ok_or_else(|| "pyproject.toml must contain a top-level table.".to_string())?;
    let project = root
        .entry("project".to_string())
        .or_insert_with(|| toml::Value::Table(toml::map::Map::new()))
        .as_table_mut()
        .ok_or_else(|| "pyproject.toml [project] must be a table.".to_string())?;
    project.insert(
        "description".to_string(),
        toml::Value::String(profile.description.to_string()),
    );
    project.insert(
        "license".to_string(),
        toml::Value::String(profile.license.to_string()),
    );
    project.insert(
        "license-files".to_string(),
        toml::Value::Array(
            profile
                .license_files
                .iter()
                .map(|value| toml::Value::String((*value).to_string()))
                .collect(),
        ),
    );
    project.insert(
        "keywords".to_string(),
        toml::Value::Array(
            profile
                .keywords
                .iter()
                .map(|value| toml::Value::String((*value).to_string()))
                .collect(),
        ),
    );
    project.insert(
        "classifiers".to_string(),
        toml::Value::Array(
            profile
                .classifiers
                .iter()
                .map(|value| toml::Value::String((*value).to_string()))
                .collect(),
        ),
    );
    let urls = [
        ("Homepage", "https://ait-native.dev"),
        ("Documentation", "https://ait-native.dev"),
        ("Source", "https://github.com/weita2026/ait-native"),
        ("Issues", "https://github.com/weita2026/ait-native/issues"),
        (
            "Releases",
            "https://github.com/weita2026/ait-native/releases",
        ),
    ]
    .into_iter()
    .map(|(key, value)| (key.to_string(), toml::Value::String(value.to_string())))
    .collect::<toml::map::Map<String, toml::Value>>();
    project.insert("urls".to_string(), toml::Value::Table(urls));
    if let Some(readme_file) = profile.readme_file {
        let mut readme = toml::map::Map::new();
        readme.insert(
            "file".to_string(),
            toml::Value::String(readme_file.to_string()),
        );
        readme.insert(
            "content-type".to_string(),
            toml::Value::String("text/markdown".to_string()),
        );
        project.insert("readme".to_string(), toml::Value::Table(readme));
    }
    let scripts = project
        .entry("scripts".to_string())
        .or_insert_with(|| toml::Value::Table(toml::map::Map::new()))
        .as_table_mut()
        .ok_or_else(|| "pyproject.toml [project.scripts] must be a table.".to_string())?;
    for script in profile.forbidden_scripts {
        scripts.remove(*script);
    }
    toml::to_string_pretty(&data).map_err(|err| err.to_string())
}

pub(super) fn package_metadata_from_bundle(
    bundle: &ReleaseBundle,
) -> Result<PackageMetadata, String> {
    let entry = bundle.files.get("pyproject.toml").ok_or_else(|| {
        "Release source snapshot is missing required file: pyproject.toml".to_string()
    })?;
    let data = String::from_utf8(entry.data.clone()).map_err(|err| err.to_string())?;
    let parsed = data.parse::<toml::Value>().map_err(|err| err.to_string())?;
    let project = parsed
        .get("project")
        .and_then(toml::Value::as_table)
        .ok_or_else(|| "pyproject.toml must define [project].".to_string())?;
    let name = toml_string(project.get("name")).ok_or_else(|| {
        "pyproject.toml must define project.name and project.version for release candidates."
            .to_string()
    })?;
    let version = toml_string(project.get("version")).ok_or_else(|| {
        "pyproject.toml must define project.name and project.version for release candidates."
            .to_string()
    })?;
    let scripts = project
        .get("scripts")
        .and_then(toml::Value::as_table)
        .map(|table| {
            table
                .iter()
                .filter_map(|(key, value)| {
                    toml_string(Some(value)).map(|value| (key.clone(), value))
                })
                .collect::<BTreeMap<_, _>>()
        })
        .unwrap_or_default();
    let urls = project
        .get("urls")
        .and_then(toml::Value::as_table)
        .map(|table| {
            table
                .iter()
                .filter_map(|(key, value)| {
                    toml_string(Some(value)).map(|value| (key.clone(), value))
                })
                .collect::<BTreeMap<_, _>>()
        })
        .unwrap_or_default();
    Ok(PackageMetadata {
        name,
        version,
        description: toml_string(project.get("description")),
        readme: toml_to_json(project.get("readme")),
        requires_python: toml_string(project.get("requires-python")),
        license: toml_string(project.get("license")),
        license_files: toml_string_list(project.get("license-files")),
        dependencies: toml_string_list(project.get("dependencies")),
        scripts,
        urls,
        classifiers: toml_string_list(project.get("classifiers")),
        keywords: toml_string_list(project.get("keywords")),
    })
}

pub(super) fn apply_release_notes(
    repo: &RepoRuntime,
    record: &JsonValue,
    bundle: &mut ReleaseBundle,
) -> Result<(), String> {
    let Some(readme) = bundle.files.get("README.md").cloned() else {
        return Ok(());
    };
    let mut text = String::from_utf8(readme.data).map_err(|err| err.to_string())?;
    let version = required_string_field(record, "version")?;
    let notes = render_release_notes(repo, record)?;
    text.push_str(&format!(
        "\n<!-- ait-release-notes:start -->\n## Release Notes\n\n### v{version}\n{notes}\n<!-- ait-release-notes:end -->\n"
    ));
    bundle.files.insert(
        "README.md".to_string(),
        BundleEntry {
            path: "README.md".to_string(),
            data: text.into_bytes(),
            mode: readme.mode,
        },
    );
    Ok(())
}

pub(super) fn render_release_notes(
    repo: &RepoRuntime,
    record: &JsonValue,
) -> Result<String, String> {
    let previous = previous_published_release(repo, record)?;
    let Some(previous) = previous else {
        return Ok("Initial published release for this profile.\n".to_string());
    };
    let previous_version = required_string_field(&previous, "version").unwrap_or_default();
    let tasks = landed_tasks_since_previous_release(repo, &previous)?;
    if tasks.is_empty() {
        return Ok(format!(
            "No finished task records were found since `v{previous_version}`.\n"
        ));
    }
    let mut lines = vec![format!(
        "Tasks finished since `v{previous_version}` ({} task{}):",
        tasks.len(),
        if tasks.len() == 1 { "" } else { "s" }
    )];
    for task in tasks {
        lines.push(format!(
            "- `{}` {}",
            required_string_field(&task, "task_id").unwrap_or_default(),
            required_string_field(&task, "title").unwrap_or_default()
        ));
    }
    Ok(lines.join("\n") + "\n")
}

pub(super) fn previous_published_release(
    repo: &RepoRuntime,
    record: &JsonValue,
) -> Result<Option<JsonValue>, String> {
    let version = required_string_field(record, "version")?;
    let release_store = workflow_release_store(repo)?;
    latest_published_workflow_release_excluding_version_with_store(&release_store, &version)?
        .map(|record| hydrate_release(release_candidate_record_json(&record)))
        .transpose()
}

pub(super) fn landed_tasks_since_previous_release(
    repo: &RepoRuntime,
    _previous: &JsonValue,
) -> Result<Vec<JsonValue>, String> {
    let task_store = release_task_store(repo)?;
    list_completed_tasks_with_landed_changes_with_task_store(&task_store)
        .map_err(|err| err.to_string())
}

pub(super) fn build_sdist(
    source_dir: &Path,
    dist_dir: &Path,
    package: &PackageMetadata,
    epoch: i64,
) -> Result<PathBuf, String> {
    let filename = format!("{}-{}.tar.gz", package.name, package.version);
    let target = dist_dir.join(filename);
    let file = File::create(&target).map_err(io_error)?;
    let encoder: GzEncoder<File> = GzBuilder::new()
        .mtime(epoch.max(0) as u32)
        .write(file, Compression::default());
    let mut tar = TarBuilder::new(encoder);
    let root_name = format!("{}-{}", package.name, package.version);
    append_tar_bytes(
        &mut tar,
        &format!("{root_name}/PKG-INFO"),
        distribution_metadata(source_dir, package)?.0.as_bytes(),
        0o644,
        epoch,
    )?;
    for path in recursive_files(source_dir)? {
        let rel = path
            .strip_prefix(source_dir)
            .map_err(|err| err.to_string())?
            .to_string_lossy()
            .replace('\\', "/");
        if rel.contains("__pycache__") {
            continue;
        }
        let data = fs::read(&path).map_err(io_error)?;
        let mode = filesystem_mode(&path.metadata().map_err(io_error)?, 0o644);
        append_tar_bytes(&mut tar, &format!("{root_name}/{rel}"), &data, mode, epoch)?;
    }
    let encoder = tar.into_inner().map_err(io_error)?;
    encoder.finish().map_err(io_error)?;
    Ok(target)
}

pub(super) fn append_tar_bytes<W: Write>(
    tar: &mut TarBuilder<W>,
    path: &str,
    data: &[u8],
    mode: u32,
    epoch: i64,
) -> Result<(), String> {
    let mut header = Header::new_gnu();
    header.set_size(data.len() as u64);
    header.set_mode(mode);
    header.set_mtime(epoch.max(0) as u64);
    header.set_uid(0);
    header.set_gid(0);
    header.set_cksum();
    tar.append_data(&mut header, path, data).map_err(io_error)
}

pub(super) fn build_wheel(
    source_dir: &Path,
    dist_dir: &Path,
    package: &PackageMetadata,
    _epoch: i64,
) -> Result<PathBuf, String> {
    let dist_name = distribution_name(&package.name, true);
    let filename = format!("{}-{}-py3-none-any.whl", dist_name, package.version);
    let target = dist_dir.join(filename);
    let file = File::create(&target).map_err(io_error)?;
    let mut zf = zip::ZipWriter::new(file);
    let options = zip_options();
    let source_root = wheel_source_root(source_dir)?;
    let mut records = Vec::<(String, Vec<u8>)>::new();
    for path in recursive_files(&source_root)? {
        let rel = path
            .strip_prefix(&source_root)
            .map_err(|err| err.to_string())?
            .to_string_lossy()
            .replace('\\', "/");
        if rel.contains("__pycache__") {
            continue;
        }
        let data = fs::read(&path).map_err(io_error)?;
        zf.start_file(&rel, options).map_err(zip_error)?;
        zf.write_all(&data).map_err(io_error)?;
        records.push((rel, data));
    }
    let metadata_dir = format!("{}-{}.dist-info", dist_name, package.version);
    let (metadata, entry_points) = distribution_metadata(source_dir, package)?;
    write_zip_record(
        &mut zf,
        &mut records,
        &format!("{metadata_dir}/METADATA"),
        metadata.as_bytes(),
    )?;
    write_zip_record(
        &mut zf,
        &mut records,
        &format!("{metadata_dir}/WHEEL"),
        b"Wheel-Version: 1.0\nGenerator: ait release\nRoot-Is-Purelib: true\nTag: py3-none-any\n",
    )?;
    if !entry_points.is_empty() {
        write_zip_record(
            &mut zf,
            &mut records,
            &format!("{metadata_dir}/entry_points.txt"),
            entry_points.as_bytes(),
        )?;
    }
    for license_file in &package.license_files {
        let path = source_dir.join(license_file);
        if path.is_file() {
            let data = fs::read(&path).map_err(io_error)?;
            write_zip_record(
                &mut zf,
                &mut records,
                &format!("{metadata_dir}/licenses/{license_file}"),
                &data,
            )?;
        }
    }
    let mut record_lines = records
        .iter()
        .map(|(path, data)| {
            format!(
                "{path},sha256={},{}",
                BASE64_URL_SAFE_NO_PAD.encode(Sha256::digest(data)),
                data.len()
            )
        })
        .collect::<Vec<_>>();
    record_lines.push(format!("{metadata_dir}/RECORD,,"));
    let record_bytes = (record_lines.join("\n") + "\n").into_bytes();
    zf.start_file(format!("{metadata_dir}/RECORD"), options)
        .map_err(zip_error)?;
    zf.write_all(&record_bytes).map_err(io_error)?;
    zf.finish().map_err(zip_error)?;
    Ok(target)
}

pub(super) fn write_zip_record(
    zf: &mut zip::ZipWriter<File>,
    records: &mut Vec<(String, Vec<u8>)>,
    path: &str,
    data: &[u8],
) -> Result<(), String> {
    zf.start_file(path, zip_options()).map_err(zip_error)?;
    zf.write_all(data).map_err(io_error)?;
    records.push((path.to_string(), data.to_vec()));
    Ok(())
}

pub(super) fn zip_options() -> FileOptions {
    FileOptions::default()
        .compression_method(zip::CompressionMethod::Deflated)
        .last_modified_time(zip::DateTime::from_date_and_time(1980, 1, 1, 0, 0, 0).unwrap())
        .unix_permissions(0o644)
}

pub(super) fn distribution_metadata(
    source_dir: &Path,
    package: &PackageMetadata,
) -> Result<(String, String), String> {
    let mut lines = vec![
        "Metadata-Version: 2.4".to_string(),
        format!("Name: {}", package.name),
        format!("Version: {}", package.version),
    ];
    if let Some(value) = &package.description {
        lines.push(format!("Summary: {value}"));
    }
    if let Some(value) = &package.requires_python {
        lines.push(format!("Requires-Python: {value}"));
    }
    if let Some(value) = &package.license {
        lines.push(format!("License-Expression: {value}"));
    }
    if !package.keywords.is_empty() {
        lines.push(format!("Keywords: {}", package.keywords.join(", ")));
    }
    for (label, url) in &package.urls {
        lines.push(format!("Project-URL: {label}, {url}"));
    }
    for classifier in &package.classifiers {
        lines.push(format!("Classifier: {classifier}"));
    }
    for dep in &package.dependencies {
        lines.push(format!("Requires-Dist: {dep}"));
    }
    let (readme_body, readme_content_type) = readme_payload(source_dir, package)?;
    if let Some(content_type) = readme_content_type {
        lines.push(format!("Description-Content-Type: {content_type}"));
    }
    for license_file in &package.license_files {
        lines.push(format!("License-File: {license_file}"));
    }
    let mut metadata = lines.join("\n") + "\n";
    if let Some(body) = readme_body {
        metadata.push('\n');
        metadata.push_str(body.trim_end());
        metadata.push('\n');
    }
    let entry_points = if package.scripts.is_empty() {
        String::new()
    } else {
        let mut lines = vec!["[console_scripts]".to_string()];
        for (name, target) in &package.scripts {
            lines.push(format!("{name} = {target}"));
        }
        lines.join("\n") + "\n"
    };
    Ok((metadata, entry_points))
}

pub(super) fn readme_payload(
    source_dir: &Path,
    package: &PackageMetadata,
) -> Result<(Option<String>, Option<String>), String> {
    match package.readme.as_ref() {
        Some(JsonValue::String(path)) => {
            let body = fs::read_to_string(source_dir.join(path)).ok();
            Ok((body, readme_content_type(path)))
        }
        Some(JsonValue::Object(obj)) => {
            if let Some(text) = obj.get("text").and_then(JsonValue::as_str) {
                return Ok((Some(text.to_string()), Some("text/markdown".to_string())));
            }
            let path = obj
                .get("file")
                .and_then(JsonValue::as_str)
                .unwrap_or_default();
            let content_type = obj
                .get("content-type")
                .and_then(JsonValue::as_str)
                .map(str::to_string)
                .or_else(|| readme_content_type(path));
            let body = if path.is_empty() {
                None
            } else {
                fs::read_to_string(source_dir.join(path)).ok()
            };
            Ok((body, content_type))
        }
        _ => Ok((None, None)),
    }
}

pub(super) fn readme_content_type(path: &str) -> Option<String> {
    if path.ends_with(".md") {
        Some("text/markdown".to_string())
    } else if path.ends_with(".rst") {
        Some("text/x-rst".to_string())
    } else if path.ends_with(".txt") {
        Some("text/plain".to_string())
    } else {
        None
    }
}

pub(super) fn wheel_source_root(source_dir: &Path) -> Result<PathBuf, String> {
    let pyproject = fs::read_to_string(source_dir.join("pyproject.toml")).map_err(io_error)?;
    let parsed = pyproject
        .parse::<toml::Value>()
        .map_err(|err| err.to_string())?;
    if let Some(package_dir) = parsed
        .get("tool")
        .and_then(|v| v.get("setuptools"))
        .and_then(|v| v.get("package-dir"))
        .and_then(toml::Value::as_table)
        .and_then(|table| table.get(""))
        .and_then(toml::Value::as_str)
    {
        let root = source_dir.join(package_dir);
        if root.exists() {
            return Ok(root);
        }
    }
    let src = source_dir.join("src");
    if src.exists() {
        Ok(src)
    } else {
        Ok(source_dir.to_path_buf())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn homebrew_python_formula_is_an_explicit_bounded_name() {
        assert_eq!(
            require_homebrew_formula_name("python@3.14").unwrap(),
            "python@3.14"
        );
        for invalid in ["", " python@3", "owner/python@3", "python@3\nnext"] {
            assert!(
                require_homebrew_formula_name(invalid).is_err(),
                "{invalid:?}"
            );
        }
    }
}
