[package]
name = "ait-cli"
version.workspace = true
edition = "2021"
license.workspace = true

[[bin]]
name = "ait-cli"
path = "src/main.rs"

[features]
default = []
perfetto-tracing = ["ait-core/perfetto-tracing"]

[dependencies]
ait-core = { path = "../ait-core", default-features = false }
base64 = "0.22"
clap = { version = "4.5", features = ["derive"] }
chrono = "0.4"
flate2 = "1.0"
fs2 = "0.4"
libc = "0.2"
plist = "1.7"
sha2 = "0.10"
similar = "2.7"
tar = "0.4"
tempfile = "3.12"
tiny_http = "0.12"
toml = "0.8"
zip = "0.6.6"

[dev-dependencies]
assert_cmd = "2.0"
predicates = "3.1"
serde_json = "1.0"
tempfile = "3.12"
