pub(super) fn register(py: Python<'_>, module: &Bound<'_, PyModule>) -> PyResult<()> {
    module.add_class::<PlanRemoteTransportConfigPy>()?;
    module.add_class::<PlanHttpClientManagerPy>()?;
    module.add_class::<TaskWorkflowHttpClientManagerPy>()?;
    module.add_class::<HttpTaskRemotePy>()?;
    module.add_class::<HttpWorkflowCloseoutRemotePy>()?;
    module.add_class::<WorkspaceCommandLockPy>()?;
    register_remote_clients(py, module)?;
    register_agent_runtime(py, module)?;
    register_plan_http(py, module)?;
    register_task_workflow(py, module)?;
    register_plan_store(py, module)?;
    register_workflow_policy(py, module)?;
    register_plan_filesystem_storage(py, module)?;
    register_render_parse(py, module)?;
    module.add("contract_version", "task-close-v1")?;
    module.add("plan_contract_version", "plan-foundation-v7")?;
    module.add(
        "DEFAULT_REQUEST_TIMEOUT_SECONDS",
        DEFAULT_REQUEST_TIMEOUT_SECONDS,
    )?;
    module.add(
        "LONG_RUNNING_REQUEST_TIMEOUT_SECONDS",
        LONG_RUNNING_REQUEST_TIMEOUT_SECONDS,
    )?;
    module.add("DEFAULT_ID_NAMESPACE_PREFIX", DEFAULT_ID_NAMESPACE_PREFIX)?;
    module.add(
        "LOCAL_WORKFLOW_ID_NAMESPACE_PREFIX",
        LOCAL_WORKFLOW_ID_NAMESPACE_PREFIX,
    )?;
    module.add(
        "REMOTE_WORKFLOW_ID_NAMESPACE_PREFIX",
        REMOTE_WORKFLOW_ID_NAMESPACE_PREFIX,
    )?;
    module.add(
        "WORKFLOW_TASK_CHANGE_ORIGIN_NAMESPACE_PREFIXES",
        WORKFLOW_TASK_CHANGE_ORIGIN_NAMESPACE_PREFIXES.to_vec(),
    )?;
    module.add("WORKFLOW_ID_FAMILIES", WORKFLOW_ID_FAMILIES.to_vec())?;
    module.add(
        "POLICY_REQUIREMENT_FLAGS",
        rust_policy::POLICY_REQUIREMENT_FLAGS.to_vec(),
    )?;
    module.add(
        "POLICY_CONTENT_CLASSES",
        rust_policy::POLICY_CONTENT_CLASSES.to_vec(),
    )?;
    module.add(
        "POLICY_AUTHOR_CLASSES",
        rust_policy::POLICY_AUTHOR_CLASSES.to_vec(),
    )?;
    module.add(
        "CODE_REVIEW_SUMMARY_TEMPLATE",
        rust_policy::CODE_REVIEW_SUMMARY_TEMPLATE,
    )?;
    module.add(
        "CODE_REVIEW_SUMMARY_NUMBERED_TEMPLATE",
        rust_policy::CODE_REVIEW_SUMMARY_NUMBERED_TEMPLATE,
    )?;
    module.add(
        "CODE_REVIEW_SUMMARY_TEMPLATE_HINT_COMMAND",
        rust_policy::CODE_REVIEW_SUMMARY_TEMPLATE_HINT_COMMAND,
    )?;
    module.add("RUNTIME_DATA_ENV", rust_runtime_roots::RUNTIME_DATA_ENV)?;
    module.add(
        "LEGACY_SERVER_DATA_ENV",
        rust_runtime_roots::LEGACY_SERVER_DATA_ENV,
    )?;
    module.add("package_version", env!("CARGO_PKG_VERSION"))?;
    module.add("target_triple", rustc_target())?;
    let version = py.version_info();
    module.add(
        "python_tag",
        format!("cp{}{}", version.major, version.minor),
    )?;
    module.add(
        "normalize_remote_text",
        module.getattr("normalize_remote_text")?,
    )?;
    module.add("join_path", module.getattr("join_path")?)?;
    module.add("build_query_string", module.getattr("build_query_string")?)?;
    module.add(
        "build_list_plans_request",
        module.getattr("build_list_plans_request")?,
    )?;
    module.add(
        "build_get_plan_request",
        module.getattr("build_get_plan_request")?,
    )?;
    module.add(
        "build_list_plan_revisions_request",
        module.getattr("build_list_plan_revisions_request")?,
    )?;
    module.add(
        "build_get_plan_revision_request",
        module.getattr("build_get_plan_revision_request")?,
    )?;
    module.add(
        "build_create_plan_request",
        module.getattr("build_create_plan_request")?,
    )?;
    module.add(
        "build_revise_plan_request",
        module.getattr("build_revise_plan_request")?,
    )?;
    module.add(
        "build_update_plan_status_request",
        module.getattr("build_update_plan_status_request")?,
    )?;
    module.add(
        "build_put_plan_revision_artifacts_request",
        module.getattr("build_put_plan_revision_artifacts_request")?,
    )?;
    module.add("plan_http_list_plans", module.getattr("list_plans")?)?;
    module.add("plan_http_get_plan", module.getattr("get_plan")?)?;
    module.add(
        "plan_http_list_plan_revisions",
        module.getattr("list_plan_revisions")?,
    )?;
    module.add(
        "plan_http_get_plan_revision",
        module.getattr("get_plan_revision")?,
    )?;
    module.add("plan_http_create_plan", module.getattr("create_plan")?)?;
    module.add("plan_http_revise_plan", module.getattr("revise_plan")?)?;
    module.add(
        "plan_http_update_plan_status",
        module.getattr("update_plan_status")?,
    )?;
    module.add(
        "plan_http_put_plan_revision_artifacts",
        module.getattr("put_plan_revision_artifacts")?,
    )?;
    module.add(
        "plan_http_resolve_task_plan_linkage",
        module.getattr("resolve_task_plan_linkage")?,
    )?;
    module.add(
        "plan_http_list_plan_ids_matching_contains",
        module.getattr("list_plan_ids_matching_contains")?,
    )?;
    module.add(
        "plan_http_create_planning_session",
        module.getattr("create_planning_session")?,
    )?;
    module.add(
        "plan_http_list_planning_sessions",
        module.getattr("list_planning_sessions")?,
    )?;
    module.add(
        "plan_http_get_planning_session",
        module.getattr("get_planning_session")?,
    )?;
    module.add(
        "plan_http_append_planning_session_event",
        module.getattr("append_planning_session_event")?,
    )?;
    module.add(
        "plan_http_list_planning_session_events",
        module.getattr("list_planning_session_events")?,
    )?;
    module.add(
        "plan_http_join_planning_session",
        module.getattr("join_planning_session")?,
    )?;
    module.add(
        "plan_http_promote_planning_session",
        module.getattr("promote_planning_session")?,
    )?;
    module.add(
        "plan_http_close_planning_session",
        module.getattr("close_planning_session")?,
    )?;
    module.add("resolve_task_close", module.getattr("resolve_task_close")?)?;
    #[cfg(test)]
    {
        module.add(
            "list_task_store_tasks",
            module.getattr("list_task_store_tasks")?,
        )?;
    module.add(
        "get_task_store_task",
        module.getattr("get_task_store_task")?,
    )?;
    module.add(
        "allocate_task_store_task_identity",
        module.getattr("allocate_task_store_task_identity")?,
    )?;
    module.add(
        "get_task_store_sequence_floor",
        module.getattr("get_task_store_sequence_floor")?,
    )?;
    module.add(
        "create_task_store_task",
        module.getattr("create_task_store_task")?,
    )?;
    module.add(
        "create_task_store_task_explicit",
        module.getattr("create_task_store_task_explicit")?,
    )?;
    module.add(
        "close_task_store_task",
        module.getattr("close_task_store_task")?,
    )?;
    module.add(
        "mark_task_store_task_published",
        module.getattr("mark_task_store_task_published")?,
    )?;
    module.add(
        "list_change_store_changes",
        module.getattr("list_change_store_changes")?,
    )?;
    module.add(
        "get_change_store_change",
        module.getattr("get_change_store_change")?,
    )?;
    module.add(
        "allocate_change_store_change_identity",
        module.getattr("allocate_change_store_change_identity")?,
    )?;
    module.add(
        "create_change_store_change",
        module.getattr("create_change_store_change")?,
    )?;
    module.add(
        "create_change_store_change_explicit",
        module.getattr("create_change_store_change_explicit")?,
    )?;
    module.add(
        "close_change_store_change",
        module.getattr("close_change_store_change")?,
    )?;
    module.add(
        "land_change_store_change",
        module.getattr("land_change_store_change")?,
    )?;
    module.add(
        "mark_change_store_change_published",
        module.getattr("mark_change_store_change_published")?,
    )?;
    }
    module.add(
        "task_remote_change_lineage_payload",
        module.getattr("task_remote_change_lineage_payload")?,
    )?;
    module.add(
        "project_workflow_landed_read_model",
        module.getattr("project_workflow_landed_read_model")?,
    )?;
    module.add(
        "project_workflow_land_full_read_model",
        module.getattr("project_workflow_land_full_read_model")?,
    )?;
    module.add(
        "project_workflow_ready_read_model",
        module.getattr("project_workflow_ready_read_model")?,
    )?;
    module.add(
        "project_workflow_land_phase_read_model",
        module.getattr("project_workflow_land_phase_read_model")?,
    )?;
    module.add(
        "workflow_remote_mutation_receipt",
        module.getattr("workflow_remote_mutation_receipt")?,
    )?;
    module.add(
        "workflow_remote_action_mutation_receipts",
        module.getattr("workflow_remote_action_mutation_receipts")?,
    )?;
    module.add(
        "workflow_apply_phase_payload",
        module.getattr("workflow_apply_phase_payload")?,
    )?;
    module.add(
        "workflow_apply_phase_summary",
        module.getattr("workflow_apply_phase_summary")?,
    )?;
    module.add(
        "workflow_mutation_receipt_summary",
        module.getattr("workflow_mutation_receipt_summary")?,
    )?;
    module.add(
        "workflow_applied_action_summary",
        module.getattr("workflow_applied_action_summary")?,
    )?;
    module.add("extract_plan_items", module.getattr("extract_plan_items")?)?;
    module.add(
        "list_plan_section_refs",
        module.getattr("list_plan_section_refs")?,
    )?;
    module.add(
        "extract_plan_section",
        module.getattr("extract_plan_section")?,
    )?;
    module.add("find_plan_item", module.getattr("find_plan_item")?)?;
    module.add(
        "normalize_plan_items",
        module.getattr("normalize_plan_items")?,
    )?;
    module.add(
        "find_plan_item_in_items",
        module.getattr("find_plan_item_in_items")?,
    )?;
    module.add("plan_items_payload", module.getattr("plan_items_payload")?)?;
    module.add(
        "local_plan_publish_shadow",
        module.getattr("local_plan_publish_shadow")?,
    )?;
    module.add(
        "plan_dispatch_summary",
        module.getattr("plan_dispatch_summary")?,
    )?;
    module.add(
        "plan_task_link_indexes",
        module.getattr("plan_task_link_indexes")?,
    )?;
    module.add(
        "compute_taskable_items",
        module.getattr("compute_taskable_items")?,
    )?;
    module.add(
        "validate_dispatch_legality",
        module.getattr("validate_dispatch_legality")?,
    )?;
    module.add(
        "plan_candidates_payload",
        module.getattr("plan_candidates_payload")?,
    )?;
    #[cfg(test)]
    {
        module.add(
            "list_workflow_plans",
            module.getattr("list_workflow_plans")?,
        )?;
    module.add("get_workflow_plan", module.getattr("get_workflow_plan")?)?;
    module.add(
        "list_workflow_plan_revisions",
        module.getattr("list_workflow_plan_revisions")?,
    )?;
    module.add(
        "get_workflow_plan_revision",
        module.getattr("get_workflow_plan_revision")?,
    )?;
    module.add(
        "get_workflow_plan_revision_by_id",
        module.getattr("get_workflow_plan_revision_by_id")?,
    )?;
    module.add(
        "create_workflow_plan",
        module.getattr("create_workflow_plan")?,
    )?;
    module.add(
        "revise_workflow_plan",
        module.getattr("revise_workflow_plan")?,
    )?;
    module.add(
        "close_workflow_plan",
        module.getattr("close_workflow_plan")?,
    )?;
    module.add(
        "rekey_workflow_plan",
        module.getattr("rekey_workflow_plan")?,
    )?;
    module.add(
        "mark_workflow_plan_published",
        module.getattr("mark_workflow_plan_published")?,
    )?;
    module.add(
        "inspect_plan_storage_readiness",
        module.getattr("inspect_plan_storage_readiness")?,
    )?;
    }
    module.add(
        "normalize_task_status",
        module.getattr("normalize_task_status")?,
    )?;
    module.add(
        "task_status_details",
        module.getattr("task_status_details")?,
    )?;
    module.add(
        "normalize_workflow_mode",
        module.getattr("normalize_workflow_mode")?,
    )?;
    module.add(
        "normalize_publication_state",
        module.getattr("normalize_publication_state")?,
    )?;
    module.add(
        "publication_state_has_unpublished_head",
        module.getattr("publication_state_has_unpublished_head")?,
    )?;
    module.add("workflow_id_token", module.getattr("workflow_id_token")?)?;
    module.add(
        "workflow_id_matches",
        module.getattr("workflow_id_matches")?,
    )?;
    module.add(
        "generate_namespaced_sequence_id",
        module.getattr("generate_namespaced_sequence_id")?,
    )?;
    module.add(
        "workflow_success_envelope",
        module.getattr("workflow_success_envelope")?,
    )?;
    module.add(
        "workflow_error_envelope",
        module.getattr("workflow_error_envelope")?,
    )?;
    module.add(
        "parse_plan_markdown",
        module.getattr("parse_plan_markdown")?,
    )?;
    module.add("extract_plan_refs", module.getattr("extract_plan_refs")?)?;
    module.add(
        "compute_sync_prune_decisions",
        module.getattr("compute_sync_prune_decisions")?,
    )?;
    module.add(
        "diff_snapshot_manifests",
        module.getattr("diff_snapshot_manifests")?,
    )?;
    module.add(
        "plan_blob_diff_diff_snapshot_manifests",
        module.getattr("diff_snapshot_manifests")?,
    )?;
    module.add(
        "snapshot_diff_from_manifests",
        module.getattr("snapshot_diff_from_manifests")?,
    )?;
    module.add(
        "plan_blob_diff_snapshot_diff_from_manifests",
        module.getattr("snapshot_diff_from_manifests")?,
    )?;
    module.add("artifact_blob_id", module.getattr("artifact_blob_id")?)?;
    module.add(
        "plan_blob_diff_artifact_blob_id",
        module.getattr("artifact_blob_id")?,
    )?;
    module.add(
        "artifact_candidates_open",
        module.getattr("artifact_candidates_open")?,
    )?;
    module.add(
        "plan_blob_diff_artifact_candidates_open",
        module.getattr("artifact_candidates_open")?,
    )?;
    module.add(
        "plan_artifact_identity",
        module.getattr("plan_artifact_identity")?,
    )?;
    module.add(
        "plan_blob_diff_plan_artifact_identity",
        module.getattr("plan_artifact_identity")?,
    )?;
    module.add(
        "plan_artifact_identity_label",
        module.getattr("plan_artifact_identity_label")?,
    )?;
    module.add(
        "plan_blob_diff_plan_artifact_identity_label",
        module.getattr("plan_artifact_identity_label")?,
    )?;
    module.add(
        "index_plans_by_artifact_path",
        module.getattr("index_plans_by_artifact_path")?,
    )?;
    module.add(
        "plan_blob_diff_index_plans_by_artifact_path",
        module.getattr("index_plans_by_artifact_path")?,
    )?;
    module.add(
        "index_plans_by_artifact_identity",
        module.getattr("index_plans_by_artifact_identity")?,
    )?;
    module.add(
        "plan_blob_diff_index_plans_by_artifact_identity",
        module.getattr("index_plans_by_artifact_identity")?,
    )?;
    module.add(
        "open_generic_plans_matching_blob_id",
        module.getattr("open_generic_plans_matching_blob_id")?,
    )?;
    module.add(
        "plan_blob_diff_open_generic_plans_matching_blob_id",
        module.getattr("open_generic_plans_matching_blob_id")?,
    )?;
    module.add(
        "open_plans_matching_selector",
        module.getattr("open_plans_matching_selector")?,
    )?;
    module.add(
        "plan_blob_diff_open_plans_matching_selector",
        module.getattr("open_plans_matching_selector")?,
    )?;
    module.add(
        "local_plan_fully_published",
        module.getattr("local_plan_fully_published")?,
    )?;
    module.add(
        "plan_blob_diff_local_plan_fully_published",
        module.getattr("local_plan_fully_published")?,
    )?;
    module.add(
        "plan_heads_equivalent",
        module.getattr("plan_heads_equivalent")?,
    )?;
    module.add(
        "plan_blob_diff_plan_heads_equivalent",
        module.getattr("plan_heads_equivalent")?,
    )?;
    module.add(
        "plan_matches_sync_artifact",
        module.getattr("plan_matches_sync_artifact")?,
    )?;
    module.add(
        "plan_blob_diff_plan_matches_sync_artifact",
        module.getattr("plan_matches_sync_artifact")?,
    )?;
    Ok(())
}

fn rustc_target() -> String {
    option_env!("TARGET")
        .unwrap_or("unknown-target")
        .to_string()
}
