class AitNative < Formula
  preserve_rpath

  desc "Agent-first Markdown workflow CLI with optional self-hosted server and worker surfaces"
  homepage "https://ait-native.dev"
  url "https://github.com/weita2026/ait-native/releases/download/v0.10.6/ait_native-0.10.6-py3-none-any.whl"
  sha256 "49b8fb182efa43cb1c8deead4ccf473315f472db347ffb3ac22ebbf2e9e19a10"
  license all_of: ["Apache-2.0", "AGPL-3.0-only"]

  depends_on "python@3.14"

  def install
    system Formula["python@3.14"].opt_bin/"python3", "-m", "venv", libexec
    wheel = buildpath/"ait_native-0.10.6-py3-none-any.whl"
    cp cached_download, wheel
    system libexec/"bin/python", "-m", "pip", "install", wheel
    bin.install_symlink libexec/"bin/ait"
    bin.install_symlink libexec/"bin/ait-agent"
    bin.install_symlink libexec/"bin/ait-server"
    bin.install_symlink libexec/"bin/ait-worker"
    bin.install_symlink libexec/"bin/aitk"
  end

  def caveats
    <<~EOS
      Homebrew tap formula generated by `ait release formula`.
      Expected console scripts from this package: ait, ait-agent, ait-server, ait-worker, aitk.
      This draft intentionally avoids auto-starting services.
      `ait-server` and `ait-worker` still require self-hosted runtime configuration.
    EOS
  end
end
