//! `ait task quick`: generate a minimal sprint card and start the bound Task.
//!
//! The lineage chain (Plan -> sprint card -> Task) stays complete; only the
//! hand-authored card is replaced by a deterministic generated one.

use super::*;
use crate::primitives::task_start_from::{
    task_start_from_with_edit_root_and_progress, validate_quick_task_title,
};
use crate::primitives::worktree::task_start_context_preflight;

pub(crate) const QUICK_SPRINT_CARD_DIRECTORY: &str = "docs/sprints";
pub(crate) const QUICK_TASK_REQUIRES_SPRINT_MESSAGE: &str = "`ait task quick` requires sprint mode because it binds the Task to a generated sprint card. Use `ait task start --title <title> --intent <intent>` while sprint mode is off, or enable it with `ait config set --sprint on`.";
const QUICK_SLUG_PREFIX: &str = "quick-";
const QUICK_SLUG_MAX_CHARS: usize = 48;
const QUICK_CARD_SUFFIX_LIMIT: usize = 999;

#[derive(Clone, Debug, PartialEq, Eq)]
pub(crate) struct QuickSprintCard {
    pub artifact_path: String,
    pub plan_ref: String,
    pub item_ref: String,
    pub source: String,
    pub markdown: String,
}

/// Lower-case ASCII slug: letters and digits kept, everything else collapsed
/// into single hyphens, bounded to a stable length.
pub(crate) fn quick_card_slug(title: &str) -> String {
    let mut slug = String::new();
    let mut pending_hyphen = false;
    for character in title.chars() {
        if character.is_ascii_alphanumeric() {
            if pending_hyphen && !slug.is_empty() {
                slug.push('-');
            }
            pending_hyphen = false;
            slug.push(character.to_ascii_lowercase());
        } else {
            pending_hyphen = true;
        }
        if slug.chars().count() >= QUICK_SLUG_MAX_CHARS {
            break;
        }
    }
    let slug = slug.trim_matches('-').to_string();
    if slug.is_empty() {
        "task".to_string()
    } else {
        slug
    }
}

fn heading_safe(text: &str) -> String {
    text.split_whitespace()
        .collect::<Vec<_>>()
        .join(" ")
        .replace('[', "(")
        .replace(']', ")")
}

pub(crate) fn render_quick_sprint_card(title: &str, intent: &str, slug: &str) -> QuickSprintCard {
    let title = heading_safe(title);
    let intent = heading_safe(intent);
    let plan_ref = format!("{slug}/root");
    let item_ref = format!("{slug}/task");
    let artifact_path = format!("{QUICK_SPRINT_CARD_DIRECTORY}/{slug}.md");
    let markdown = format!(
        "# {title} [plan-ref: {plan_ref}]\n\nStatus: quick Task card generated by `ait task quick`.\nScope: {intent}\n\n- [ ] {title} [ref: {item_ref}]\n"
    );
    QuickSprintCard {
        source: format!("{artifact_path}#{item_ref}"),
        artifact_path,
        plan_ref,
        item_ref,
        markdown,
    }
}

/// Pick the card for this title: reuse an identical existing generated card,
/// otherwise the first free `quick-<slug>[-N].md` path.
pub(crate) fn select_quick_sprint_card(
    root: &Path,
    title: &str,
    intent: &str,
) -> Result<(QuickSprintCard, bool), String> {
    let base_slug = format!("{QUICK_SLUG_PREFIX}{}", quick_card_slug(title));
    let mut suffix = 0_usize;
    loop {
        let slug = if suffix == 0 {
            base_slug.clone()
        } else {
            format!("{base_slug}-{suffix}")
        };
        let card = render_quick_sprint_card(title, intent, &slug);
        let absolute = root.join(&card.artifact_path);
        if !absolute.exists() {
            return Ok((card, false));
        }
        let existing = fs::read_to_string(&absolute).map_err(|error| {
            format!(
                "Failed to read existing sprint card {}: {error}",
                card.artifact_path
            )
        })?;
        if existing == card.markdown {
            return Ok((card, true));
        }
        suffix += 1;
        if suffix > QUICK_CARD_SUFFIX_LIMIT {
            return Err(format!(
                "Could not allocate a free `{QUICK_SPRINT_CARD_DIRECTORY}/{base_slug}-N.md` card path; remove stale generated cards first."
            ));
        }
    }
}

#[allow(clippy::too_many_arguments)]
pub(crate) fn task_quick_with_edit_root_and_progress(
    repo: &RepoRuntime,
    title: Option<&str>,
    intent: &str,
    local: bool,
    remote_name: Option<&str>,
    explicit_edit_root: Option<&Path>,
    progress: Option<&mut TaskStartProgressEmitter<'_>>,
) -> Result<JsonValue, String> {
    if !repo.sprint_enabled() {
        return Err(QUICK_TASK_REQUIRES_SPRINT_MESSAGE.to_string());
    }
    // Every start guard runs before the card exists, so a refused start never
    // leaves a stray generated card behind.
    task_start_context_preflight(repo)?;
    let intent = normalized_text(Some(intent))
        .ok_or_else(|| "Task intent must not be empty.".to_string())?;
    let title = validate_quick_task_title(title.unwrap_or(&intent))?;
    let root = repo.authoritative_repo_root();
    let (card, reused) = select_quick_sprint_card(&root, &title, &intent)?;
    let absolute = root.join(&card.artifact_path);
    if !reused {
        if let Some(parent) = absolute.parent() {
            fs::create_dir_all(parent).map_err(|error| {
                format!(
                    "Failed to create sprint card directory {}: {error}",
                    parent.display()
                )
            })?;
        }
        fs::write(&absolute, &card.markdown).map_err(|error| {
            format!(
                "Failed to write generated sprint card {}: {error}",
                card.artifact_path
            )
        })?;
    }
    let mut payload = task_start_from_with_edit_root_and_progress(
        repo,
        &card.source,
        &intent,
        local,
        remote_name,
        explicit_edit_root,
        None,
        progress,
    )
    .map_err(|error| {
        format!(
            "{error} The generated sprint card remains at `{}`; after fixing the cause, rerun `ait task quick` with the same title, or run `ait task start --from {} --intent \"{intent}\"`.",
            card.artifact_path, card.source
        )
    })?;
    if let Some(object) = payload.as_object_mut() {
        object.insert(
            "quick_card".to_string(),
            json!({
                "artifact_path": card.artifact_path,
                "plan_ref": card.plan_ref,
                "item_ref": card.item_ref,
                "source": card.source,
                "reused_existing_card": reused,
            }),
        );
    }
    Ok(payload)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn slug_is_lowercase_hyphenated_and_bounded() {
        assert_eq!(
            quick_card_slug("Fix stale README badge"),
            "fix-stale-readme-badge"
        );
        assert_eq!(quick_card_slug("  --Weird__Title!!  "), "weird-title");
        assert_eq!(quick_card_slug("修正 中文 標題"), "task");
        let long = "a".repeat(200);
        assert_eq!(quick_card_slug(&long).chars().count(), QUICK_SLUG_MAX_CHARS);
    }

    #[test]
    fn rendered_card_carries_one_plan_ref_and_one_item_ref() {
        let card = render_quick_sprint_card(
            "Fix [stale] badge",
            "Update the README badge to the 1.1.4 release",
            "quick-fix-stale-badge",
        );
        assert_eq!(card.artifact_path, "docs/sprints/quick-fix-stale-badge.md");
        assert_eq!(card.plan_ref, "quick-fix-stale-badge/root");
        assert_eq!(card.item_ref, "quick-fix-stale-badge/task");
        assert_eq!(
            card.source,
            "docs/sprints/quick-fix-stale-badge.md#quick-fix-stale-badge/task"
        );
        assert_eq!(card.markdown.matches("[plan-ref: ").count(), 1);
        assert_eq!(card.markdown.matches("[ref: ").count(), 1);
        assert!(card
            .markdown
            .starts_with("# Fix (stale) badge [plan-ref: quick-fix-stale-badge/root]\n"));
        assert!(card
            .markdown
            .contains("- [ ] Fix (stale) badge [ref: quick-fix-stale-badge/task]\n"));
        let parsed = ait_core::plan_foundation::parse_plan_markdown(Some(&card.markdown));
        assert_eq!(parsed.plan_ref_count, 1, "{parsed:?}");
        assert_eq!(parsed.item_count, 1, "{parsed:?}");
    }

    #[test]
    fn card_selection_reuses_identical_cards_and_suffixes_conflicts() {
        let temp = tempfile::TempDir::new().unwrap();
        let root = temp.path();
        let (first, reused) = select_quick_sprint_card(root, "Same title", "intent one").unwrap();
        assert!(!reused);
        assert_eq!(first.artifact_path, "docs/sprints/quick-same-title.md");
        fs::create_dir_all(root.join(QUICK_SPRINT_CARD_DIRECTORY)).unwrap();
        fs::write(root.join(&first.artifact_path), &first.markdown).unwrap();
        let (again, reused) = select_quick_sprint_card(root, "Same title", "intent one").unwrap();
        assert!(reused);
        assert_eq!(again.artifact_path, first.artifact_path);
        let (other, reused) = select_quick_sprint_card(root, "Same title", "intent two").unwrap();
        assert!(!reused);
        assert_eq!(other.artifact_path, "docs/sprints/quick-same-title-1.md");
        assert_eq!(other.plan_ref, "quick-same-title-1/root");
    }
}
