use super::*;

pub(super) fn render_plan_items_payload_json(payload: &PlanItemsPayload) -> JsonValue {
    JsonValue::Object(JsonMap::from_iter([
        (
            "plan_id".to_string(),
            json_optional_string(payload.plan_id.as_deref()),
        ),
        (
            "plan_title".to_string(),
            json_optional_string(payload.plan_title.as_deref()),
        ),
        (
            "plan_revision_id".to_string(),
            json_optional_string(payload.plan_revision_id.as_deref()),
        ),
        (
            "revision_number".to_string(),
            json_optional_i64(payload.revision_number),
        ),
        (
            "identity_only".to_string(),
            JsonValue::Bool(payload.identity_only),
        ),
        (
            "dispatch_validation_required".to_string(),
            JsonValue::Bool(payload.dispatch_validation_required),
        ),
        (
            "dispatch_validation_hint".to_string(),
            JsonValue::String(payload.dispatch_validation_hint.clone()),
        ),
        ("item_count".to_string(), json_usize(payload.item_count)),
        (
            "items".to_string(),
            JsonValue::Array(
                payload
                    .items
                    .iter()
                    .map(render_dispatch_plan_item_json)
                    .collect(),
            ),
        ),
    ]))
}

pub(super) fn render_plan_candidates_payload_json(payload: &PlanCandidatesPayload) -> JsonValue {
    JsonValue::Object(JsonMap::from_iter([
        (
            "scope".to_string(),
            JsonValue::String(payload.scope.clone()),
        ),
        (
            "remote".to_string(),
            json_optional_string(payload.remote.as_deref()),
        ),
        (
            "repo_name".to_string(),
            json_optional_string(payload.repo_name.as_deref()),
        ),
        (
            "summary".to_string(),
            JsonValue::Object(JsonMap::from_iter([
                (
                    "scanned_plan_count".to_string(),
                    json_usize(payload.summary.scanned_plan_count),
                ),
                (
                    "candidate_plan_count".to_string(),
                    json_usize(payload.summary.candidate_plan_count),
                ),
                (
                    "open_item_count".to_string(),
                    json_usize(payload.summary.open_item_count),
                ),
                (
                    "taskable_item_count".to_string(),
                    json_usize(payload.summary.taskable_item_count),
                ),
                (
                    "linked_task_count".to_string(),
                    json_usize(payload.summary.linked_task_count),
                ),
                (
                    "local_unpublished_head_count".to_string(),
                    json_usize(payload.summary.local_unpublished_head_count),
                ),
            ])),
        ),
        (
            "candidates".to_string(),
            JsonValue::Array(
                payload
                    .candidates
                    .iter()
                    .map(render_plan_dispatch_summary_json)
                    .collect(),
            ),
        ),
    ]))
}

pub(super) fn render_plan_dispatch_summary_json(payload: &PlanDispatchSummary) -> JsonValue {
    JsonValue::Object(JsonMap::from_iter([
        (
            "plan_id".to_string(),
            json_optional_string(payload.plan_id.as_deref()),
        ),
        (
            "title".to_string(),
            json_optional_string(payload.title.as_deref()),
        ),
        (
            "status".to_string(),
            json_optional_string(payload.status.as_deref()),
        ),
        (
            "repo_name".to_string(),
            json_optional_string(payload.repo_name.as_deref()),
        ),
        (
            "artifact_path".to_string(),
            json_optional_string(payload.artifact_path.as_deref()),
        ),
        (
            "artifact_selector".to_string(),
            json_optional_string(payload.artifact_selector.as_deref()),
        ),
        (
            "artifact_heading".to_string(),
            json_optional_string(payload.artifact_heading.as_deref()),
        ),
        (
            "plan_revision_id".to_string(),
            json_optional_string(payload.plan_revision_id.as_deref()),
        ),
        (
            "revision_number".to_string(),
            json_optional_i64(payload.revision_number),
        ),
        (
            "publication_state".to_string(),
            json_optional_string(payload.publication_state.as_deref()),
        ),
        (
            "head_publication_state".to_string(),
            json_optional_string(payload.head_publication_state.as_deref()),
        ),
        (
            "published_plan_id".to_string(),
            json_optional_string(payload.published_plan_id.as_deref()),
        ),
        (
            "published_head_revision_id".to_string(),
            json_optional_string(payload.published_head_revision_id.as_deref()),
        ),
        (
            "local_publication".to_string(),
            payload
                .local_publication
                .as_ref()
                .map(render_local_plan_publish_shadow_json)
                .unwrap_or(JsonValue::Null),
        ),
        (
            "local_unpublished_head".to_string(),
            JsonValue::Bool(payload.local_unpublished_head),
        ),
        ("item_count".to_string(), json_usize(payload.item_count)),
        (
            "open_item_count".to_string(),
            json_usize(payload.open_item_count),
        ),
        (
            "done_item_count".to_string(),
            json_usize(payload.done_item_count),
        ),
        (
            "unref_open_item_count".to_string(),
            json_usize(payload.unref_open_item_count),
        ),
        (
            "linked_open_item_count".to_string(),
            json_usize(payload.linked_open_item_count),
        ),
        (
            "taskable_item_count".to_string(),
            json_usize(payload.taskable_item_count),
        ),
        (
            "linked_task_count".to_string(),
            json_usize(payload.linked_task_count),
        ),
        (
            "linked_task_status_counts".to_string(),
            JsonValue::Object(JsonMap::from_iter(
                payload
                    .linked_task_status_counts
                    .iter()
                    .map(|(key, value)| (key.clone(), json_usize(*value))),
            )),
        ),
        (
            "items".to_string(),
            JsonValue::Array(
                payload
                    .items
                    .iter()
                    .map(render_dispatch_summary_item_json)
                    .collect(),
            ),
        ),
        (
            "open_items".to_string(),
            JsonValue::Array(
                payload
                    .open_items
                    .iter()
                    .map(render_dispatch_summary_item_json)
                    .collect(),
            ),
        ),
        (
            "taskable_items".to_string(),
            JsonValue::Array(
                payload
                    .taskable_items
                    .iter()
                    .map(render_dispatch_summary_item_json)
                    .collect(),
            ),
        ),
    ]))
}

pub(super) fn render_dispatch_summary_item_json(payload: &DispatchSummaryItem) -> JsonValue {
    JsonValue::Object(JsonMap::from_iter([
        (
            "plan_item_ref".to_string(),
            json_optional_string(payload.plan_item_ref.as_deref()),
        ),
        ("text".to_string(), JsonValue::String(payload.text.clone())),
        (
            "checkbox_state".to_string(),
            JsonValue::String(payload.checkbox_state.clone()),
        ),
        (
            "heading_path".to_string(),
            JsonValue::Array(
                payload
                    .heading_path
                    .iter()
                    .map(|value| JsonValue::String(value.clone()))
                    .collect(),
            ),
        ),
        (
            "line_number".to_string(),
            JsonValue::Number(payload.line_number.into()),
        ),
        (
            "linked_tasks".to_string(),
            JsonValue::Array(
                payload
                    .linked_tasks
                    .iter()
                    .map(render_linked_task_summary_json)
                    .collect(),
            ),
        ),
        ("taskable".to_string(), JsonValue::Bool(payload.taskable)),
        (
            "taskable_blocker".to_string(),
            json_optional_string(payload.taskable_blocker.as_deref()),
        ),
    ]))
}

pub(super) fn render_dispatch_plan_item_json(payload: &DispatchPlanItemInput) -> JsonValue {
    JsonValue::Object(JsonMap::from_iter([
        (
            "plan_item_ref".to_string(),
            json_optional_string(payload.plan_item_ref.as_deref()),
        ),
        ("text".to_string(), JsonValue::String(payload.text.clone())),
        (
            "checkbox_state".to_string(),
            JsonValue::String(payload.checkbox_state.clone()),
        ),
        (
            "heading_path".to_string(),
            JsonValue::Array(
                payload
                    .heading_path
                    .iter()
                    .map(|value| JsonValue::String(value.clone()))
                    .collect(),
            ),
        ),
        (
            "line_number".to_string(),
            JsonValue::Number(payload.line_number.into()),
        ),
    ]))
}

pub(super) fn render_linked_task_summary_json(payload: &LinkedTaskSummary) -> JsonValue {
    JsonValue::Object(JsonMap::from_iter([
        (
            "task_id".to_string(),
            json_optional_string(payload.task_id.as_deref()),
        ),
        (
            "title".to_string(),
            json_optional_string(payload.title.as_deref()),
        ),
        (
            "status".to_string(),
            json_optional_string(payload.status.as_deref()),
        ),
        (
            "planning_state".to_string(),
            json_optional_string(payload.planning_state.as_deref()),
        ),
        (
            "origin_plan_revision_id".to_string(),
            json_optional_string(payload.origin_plan_revision_id.as_deref()),
        ),
        (
            "plan_drift_state".to_string(),
            json_optional_string(payload.plan_drift_state.as_deref()),
        ),
    ]))
}

pub(super) fn render_local_plan_publish_shadow_json(payload: &LocalPlanPublishShadow) -> JsonValue {
    JsonValue::Object(JsonMap::from_iter([
        (
            "plan_id".to_string(),
            json_optional_string(payload.plan_id.as_deref()),
        ),
        (
            "publication_state".to_string(),
            json_optional_string(payload.publication_state.as_deref()),
        ),
        (
            "head_publication_state".to_string(),
            json_optional_string(payload.head_publication_state.as_deref()),
        ),
        (
            "head_revision_id".to_string(),
            json_optional_string(payload.head_revision_id.as_deref()),
        ),
        (
            "head_revision_number".to_string(),
            json_optional_i64(payload.head_revision_number),
        ),
        (
            "published_plan_id".to_string(),
            json_optional_string(payload.published_plan_id.as_deref()),
        ),
        (
            "published_head_revision_id".to_string(),
            json_optional_string(payload.published_head_revision_id.as_deref()),
        ),
        (
            "unpublished_head".to_string(),
            JsonValue::Bool(payload.unpublished_head),
        ),
    ]))
}
