from __future__ import annotations

import os
import re
import shlex
import subprocess
import sys
import time
from collections import Counter
from pathlib import Path
from typing import Any, Callable, Mapping, Optional

import typer

from ait_storage.revision_trees import build_tree_records
from ait_protocol.common import (
    DEFAULT_ID_NAMESPACE_PREFIX,
    AuthorMode,
    CODE_REVIEW_SUMMARY_TEMPLATE,
    StorageIngestMode,
    build_minimum_provenance,
    code_review_summary_requirement_text,
    derive_policy_author_class,
    derive_policy_content_class,
    find_plan_item_in_items,
    generate_namespaced_sequence_id,
    is_structured_code_review_summary,
    missing_code_review_summary_sections,
    normalize_id_namespace_prefix,
    normalize_optional_text,
    utc_now,
)
from .. import local_control
from ..remote_client import (
    RemoteError,
    auth_whoami as remote_auth_whoami,
    backfill_task_tracking_sessions as remote_backfill_task_tracking_sessions,
    close_change as remote_close_change,
    close_planning_session as remote_close_planning_session,
    close_session as _remote_close_session,
    close_remote_line,
    close_task as remote_close_task,
    create_change as remote_create_change,
    create_planning_session as remote_create_planning_session,
    create_session as remote_create_session,
    create_session_turn as _remote_create_session_turn,
    create_session_checkpoint as _remote_create_session_checkpoint,
    create_stack as remote_create_stack,
    create_task as remote_create_task,
    create_waiver as remote_create_waiver,
    ensure_repository,
    ensure_task_tracking_session as remote_ensure_task_tracking_session,
    evaluate_policy as remote_evaluate_policy,
    get_attestation as remote_get_attestation,
    get_change as remote_get_change,
    get_land as remote_get_land,
    get_patchset as remote_get_patchset,
    get_policy as remote_get_policy,
    get_repository as remote_get_repository,
    get_release as remote_get_release,
    get_job as remote_get_job,
    get_remote_line,
    get_remote_snapshot,
    get_remote_snapshots_existence,
    get_plan as remote_get_plan,
    get_planning_session as remote_get_planning_session,
    get_plan_revision as remote_get_plan_revision,
    get_server_health as remote_get_server_health,
    get_server_metrics as remote_get_server_metrics,
    get_server_readiness as remote_get_server_readiness,
    get_stack as remote_get_stack,
    get_stack_graph as remote_get_stack_graph,
    get_task as remote_get_task,
    get_repository_storage as remote_get_repository_storage,
    get_session as _remote_get_session,
    get_session_checkpoint as remote_get_session_checkpoint,
    grant_roles as remote_grant_roles,
    gc_repo as remote_gc_repo,
    list_changes as remote_list_changes,
    list_jobs as remote_list_jobs,
    list_remote_lines as remote_list_lines,
    list_patchsets as remote_list_patchsets,
    list_plan_revisions as remote_list_plan_revisions,
    list_planning_session_events as remote_list_planning_session_events,
    list_planning_sessions as remote_list_planning_sessions,
    list_plans as remote_list_plans,
    list_reviews as remote_list_reviews,
    list_role_bindings as remote_list_role_bindings,
    list_session_checkpoints as _remote_list_session_checkpoints,
    list_session_events as _remote_list_session_events,
    list_sessions as remote_list_sessions,
    list_stacks as remote_list_stacks,
    list_tasks as remote_list_tasks,
    append_session_event as _remote_append_session_event,
    optimize_repo as remote_optimize_repo,
    pack_repo as remote_pack_repo,
    publish_release as remote_publish_release,
    publish_patchset as remote_publish_patchset,
    revise_plan as remote_revise_plan,
    put_remote_snapshot,
    put_attestation as remote_put_attestation,
    read_reviewer_inbox as remote_read_reviewer_inbox,
    read_repository_ci_runs as remote_read_repository_ci_runs,
    read_patchset_ci_status as remote_read_patchset_ci_status,
    read_queue_summary_bundle as remote_read_queue_summary_bundle,
    read_task_audit as remote_read_task_audit,
    read_task_queue as remote_read_task_queue,
    record_review as remote_record_review,
    retire_repo as remote_retire_repo,
    promote_planning_session as remote_promote_planning_session,
    join_planning_session as remote_join_planning_session,
    run_patchset_ci as remote_run_patchset_ci,
    run_repo_ci as remote_run_repo_ci,
    append_planning_session_event as remote_append_planning_session_event,
    request_review as remote_request_review,
    retry_land as remote_retry_land,
    select_patchset as remote_select_patchset,
    stack_add_change as remote_stack_add_change,
    stack_remove_change as remote_stack_remove_change,
    stack_reorder_change as remote_stack_reorder_change,
    submit_land as remote_submit_land,
    update_remote_line,
    resume_session as _remote_resume_session,
    reconcile_repo as remote_reconcile_repo,
    run_repo_migrations as remote_run_repo_migrations,
    update_stack as remote_update_stack,
)
from ..snapshot_diff import DEFAULT_SNAPSHOT_DIFF_MAX_BYTES, snapshot_diff as build_snapshot_diff
from ..local_content import (
    _path_is_projected_out_for_workspace,
    workspace_runtime_root_hygiene,
)
from ..workflow_conversation import infer_workflow_context
from ..task_worktree_layout import resolve_task_auto_worktree_location
from .line_transport_helpers import _pull_line
from .bootstrap_views import (
    _INIT_BOOTSTRAP_DIRECTORIES,
    _INIT_BOOTSTRAP_FILES,
    _INIT_FORBIDDEN_BOOTSTRAP_PATHS,
    _emit,
    _emit_task_creation_payload,
    _init_next_steps,
    _render_init_summary,
)
from . import task_dag_app_exports as _task_dag_app_exports
from .install_command import register_install_command
from .init_command import register_init_command
from .shared import _export_from_module
from .workflow_land_sync import (
    _attach_local_land_sync,
    _restore_repo_root_after_land,
)
from .workflow_authoring import _remote_change_lineage_payload
from .workflow_identity_helpers import (
    _aligned_remote_publish_identity_request,
    _is_remote_publish_identity_conflict,
    _local_workflow_identity_requests_explicit_remote_id,
    _remote_workflow_max_sequence,
    _require_remote_identity,
    _require_remote_workflow_identity_family,
    _workflow_sequence_for_row,
)
from .workflow_mode_config import (
    DEFAULT_CHANGE_WORKFLOW_SCOPE,
    DEFAULT_PLAN_TASK_BINDING,
    DEFAULT_TASK_WORKFLOW_SCOPE,
    DEFAULT_TASK_WORKTREE,
    DEFAULT_WORKFLOW_DEFAULT_SCOPE,
    PLAN_TASK_BINDING_MODES,
    WORKFLOW_DEFAULT_SCOPES,
    WORKFLOW_MODE_PRESETS,
    WORKFLOW_MODES,
    _configured_id_namespace_prefix,
    _configured_scope,
    _configured_workflow_mode,
    _effective_id_namespace_prefix,
    _effective_plan_task_binding,
    _effective_task_dag,
    _effective_task_worktree,
    _effective_workflow_mode,
    _effective_workflow_default_scope,
    _normalize_id_namespace_prefix_option,
    _normalize_plan_task_binding_mode,
    _normalize_task_dag_allow_multi_worker_mode,
    _normalize_task_tracking_mode,
    _normalize_toggle_mode,
    _normalize_workflow_default_scope,
    _normalize_workflow_mode,
    _plan_task_binding_config,
    _task_dag_config,
    _task_dag_multi_worker_allowed,
    _task_worktree_config,
    _workflow_default_scope_summary,
)
from .plan_dispatch_helpers import (
    _local_plan_publish_shadow,
    _local_plan_publish_shadow_index,
    _plan_dispatch_scope_payload,
    _plan_dispatch_summary,
    _plan_items_payload,
    _plan_task_link_indexes,
)
from .plan_sync_matching import (
    _artifact_blob_id,
    _artifact_candidates_open,
    _index_plans_by_artifact_identity,
    _index_plans_by_artifact_path,
    _local_plan_fully_published,
    _plan_artifact_identity_key,
    _plan_artifact_identity_label,
    _plan_heads_equivalent,
    _plan_matches_sync_artifact,
    _plan_status_is_historical,
    _select_existing_plan_for_artifact,
    _select_sync_existing_plan,
)
from .plan_sync_adoption import (
    _plan_publish_revision_metadata_matches,
    _plan_revisions_ascending,
    _plan_revision_artifact_body,
    _remote_plan_summary_to_plan,
    _resolve_local_sync_plan_candidate,
)
from .plan_publish_helpers import (
    _local_plan_publish,
    _map_equivalent_remote_plan_revision_suffix,
    _publish_synced_local_plan_results,
)
from .plan_sync_scope import (
    _preserve_workspace_paths_for_plan_sync,
)
from .plan_markdown_authoring import (
    _resolve_plan_artifact_input,
)
from .workspace_command_locking import (
    WorkspaceCommandBusyError,
    _run_locked_task_bound_authoring_command,
    _run_locked_workspace_command,
    _workspace_command_lock,
    _workspace_command_lock_path,
)
from .worktree_views import (
    _render_line_cleanup_candidates,
    _render_line_cleanup_report,
    _render_repo_status,
    _render_worktree_cleanup_candidates,
    _render_worktree_cleanup_report,
    _render_worktree_doctor,
    _render_worktree_prune_report,
    _render_worktree_sync_report,
    _render_worktrees,
    _render_workspace_status,
    _worktree_runtime_env,
    _worktree_runtime_paths,
    _worktree_shell_command,
)
from .task_worktree_guidance import (
    _attach_task_worktree_guidance,
    _render_task_worktree_guidance,
    _task_auto_worktree_source_status,
    _task_worktree_guidance,
    _task_worktree_output,
)
from .task_worktree_runtime import (
    ACTIVE_ROOT_WORKTREE_GUARD_BYPASS_PREFIXES,
    _active_root_worktree,
    _active_root_worktree_allows_task_bootstrap,
    _auto_remove_bound_worktree_after_local_land,
    _bound_task_id_for_worktree,
    _clear_active_root_worktree_binding,
    _clear_root_binding_for_completed_current_worktree,
    _current_worktree_cleanup_skip_payload,
    _guard_active_root_worktree,
    _guard_bound_task_match,
    _guard_internal_worktree_role,
    _guard_readonly_root_main,
    _guard_task_bound_authoring,
    _internal_worktree_role,
    _maybe_auto_create_task_worktree,
    _maybe_auto_remove_bound_worktree_after_land,
    _maybe_auto_remove_bound_worktree_after_task_complete,
    _readonly_root_main_enabled,
    _remove_bound_worktree_after_land,
    _repository_has_task_workflow_context,
    _set_active_root_worktree_binding,
    _strict_task_bound_authoring_enabled,
    _task_auto_worktree_bootstrap_allows_dirty_source,
    _task_identity_aliases,
)
from .workflow_boundary_sessions import (
    _append_remote_workflow_boundary_event,
    _apply_session_workspace_metadata,
    _remote_task_tracking_session_seed,
    _resolve_remote_workflow_boundary_session,
    _select_source_session_id,
    _submit_remote_land_with_boundary_event,
)
from .task_worktree_resolution import (
    _ensure_task_feature_line,
    _find_auto_created_task_worktree,
    _find_bound_task_worktree,
    _resolve_task_bound_worktree_name,
    _session_bound_worktree,
    _task_bound_worktree_name,
    _task_feature_line_name,
)
from .remote_repository_defaults import (
    _remote_error_status_code,
    _remote_tuple,
    _sync_remote_repository_defaults,
    _verify_remote_repository,
)
from .remote_session_wrappers import (
    _infer_remote_repo_name,
    remote_advance_task_dag_run,
    remote_append_session_event,
    remote_close_session,
    remote_create_session_checkpoint,
    remote_create_session_turn,
    remote_get_session,
    remote_list_session_checkpoints,
    remote_list_session_events,
    remote_resume_session,
)

from .plan_views import (
    _render_plan_candidates,
    _render_plan_detail,
    _render_plan_inspect,
    _render_plan_items,
    _render_plan_revisions,
    _render_plan_summary,
    _render_plan_sync_summary,
    _render_planning_session_detail,
    _render_planning_session_events,
    _render_planning_sessions,
)
from .reply_runtime_seam import generate_session_reply, load_reply_generation_config

from .session_views import (
    _render_checkpoints,
    _render_session_analysis,
    _render_session_events,
    _render_sessions,
)
from .queue_views import (
    _queue_actionable_local_changes,
    _queue_actionable_local_tasks,
    _queue_change_inventory,
    _queue_change_ready_to_land,
    _queue_change_reason,
    _queue_focus_change_reasons,
    _queue_local_summary,
    _render_queue_summary,
)
from .queue_summary_helpers import (
    _queue_remote_section,
    _queue_summary_payload,
)
from .plan_task_linkage import (
    _normalize_plan_task_linkage,
    _published_local_task_plan_linkage,
)
from .workflow_guides import (
    HELP_FLAGS,
    WORKFLOW_GUIDE_INVENTORY_TOP_LEVELS,
    WORKFLOW_GUIDE_LAND_TOP_LEVELS,
    WORKFLOW_GUIDE_TOPICS,
    _help_burst_turn,
    _render_workflow_guide_text,
    _workflow_guide_payload,
    _workflow_guide_topic_for_help_rows,
)
from .session_analysis_merge_helpers import (
    AIT_DUPLICATE_INVENTORY_COMMAND_PATHS,
    AIT_INVENTORY_COMMAND_PATHS,
    AIT_LAND_WORKFLOW_TOP_LEVELS,
    _analysis_id_namespace_prefix,
    _command_flag_value,
    _inventory_burst_turn,
    _land_workflow_turn,
    _looks_like_change_id,
    _looks_like_patchset_id,
    _looks_like_task_id,
    _task_audit_suggested_command,
    _task_audit_turn_merge,
    _task_start_suggested_command,
    _task_start_turn_merge,
    _workflow_land_suggested_command,
    _workflow_land_target_ids,
)
from .session_command_analysis import (
    AIT_COMMAND_GROUPS_WITH_SUBCOMMAND,
    AIT_COMMAND_WRAPPER_TOKENS,
    AIT_MODULE_NAMES,
    AIT_PREFIX_CONTROL_TOKENS,
    AIT_SHOW_COMMAND_PATHS,
    AIT_TASK_CLOSE_COMMAND_PATHS,
    AIT_TOP_LEVEL_COMMANDS,
    AIT_TURN_USER_EVENT_TYPES,
    SHELL_SEGMENT_SEPARATOR_TOKENS,
    _aggregate_turn_clusters,
    _analyze_session_ait_usage,
    _build_codex_turns,
    _build_session_turns,
    _commands_for_turn,
    _detect_repeated_command_runs,
    _extract_ait_command,
    _extract_session_ait_commands,
    _finalize_session_turn,
    _find_wrapped_ait_module,
    _find_wrapped_ait_token,
    _int_or_zero,
    _is_ait_command_token,
    _is_ait_wrapper_token,
    _is_ignorable_ait_prefix_token,
    _is_shell_duration_or_number_token,
    _is_shell_env_assignment,
    _normalize_turn_analysis_payload,
    _session_burst_clusters,
    _session_codex_optimization_hints,
    _session_command_phase,
    _session_event_command_values,
    _session_merge_opportunities,
    _session_optimization_hints,
    _session_turn_role,
    _shell_split_command,
    _signature_command_path,
    _split_shell_command_segments,
    _turn_analysis_hint_codes,
)
from .runtime_defaults import (
    _detect_actor_identity,
    _detect_model_name,
    _effective_actor_identity,
    _effective_author_mode,
    _effective_checkpoint_id,
    _effective_model_name,
    _effective_reviewer_identity,
    _effective_session_id,
    _format_identity,
    _normalize_model_name,
    _normalize_text_value,
    _parse_json_object_option,
    _parse_key_value_options,
)
from .review_submission_helpers import _latest_patchset_id
from .runtime_inspection_views import (
    _config_summary,
    _history_rows,
    _local_auth_snapshot,
    _storage_validation_view,
)
from .session_runtime_helpers import (
    _compact_dag_worker_session_turn_guard,
    _default_session_turn_title,
    _detected_editor_surface,
    _resolve_session_turn_remote_target,
)
from .task_tracking_bindings import (
    TRACKED_SESSION_CONFIG_KEYS,
    TRACKED_SESSION_SCOPES,
    _clear_tracked_session_binding,
    _clear_tracked_session_binding_if_matches,
    _default_line_name,
    _set_tracked_session_binding,
    _task_tracking_enabled,
    _task_tracking_hard_disabled,
    _task_tracking_mode,
    _task_worktree_repo_ctx,
    _touch_worktree_usage_safely,
    _tracked_session_binding,
)
from ..store import (
    RepoContext,
    add_remote,
    bind_worktree as local_bind_worktree,
    add_worktree as local_add_worktree,
    archive_line as local_archive_line,
    abort_worktree_rebase as local_abort_worktree_rebase,
    cleanup_lines as local_cleanup_lines,
    cleanup_worktrees as local_cleanup_worktrees,
    close_local_change,
    close_local_plan,
    close_local_session,
    collect_snapshot_chain,
    continue_worktree_rebase as local_continue_worktree_rebase,
    create_line,
    create_local_checkpoint,
    create_local_session,
    create_snapshot,
    create_stash,
    close_local_task,
    ensure_main_seed_mirror as local_ensure_main_seed_mirror,
    export_snapshot_bundle,
    gc_content as local_gc_content,
    content_storage_stats,
    current_line,
    get_worktree as local_get_worktree,
    get_line,
    get_local_change,
    get_local_plan,
    get_local_task,
    get_remote,
    get_snapshot,
    get_stash,
    get_local_checkpoint,
    init_repo,
    list_lines,
    list_line_cleanup_candidates as local_list_line_cleanup_candidates,
    list_local_checkpoints,
    list_local_changes,
    list_local_plans,
    list_local_plan_revisions,
    list_local_session_events,
    list_local_sessions,
    list_local_tasks,
    list_remotes,
    list_snapshots,
    list_stashes,
    list_worktree_cleanup_candidates as local_list_worktree_cleanup_candidates,
    list_worktrees as local_list_worktrees,
    load_policy,
    load_config,
    mark_local_change_published,
    mark_local_plan_published,
    mark_local_task_published,
    save_config,
    set_line_head,
    snapshot_exists,
    move_ref,
    optimize_content as local_optimize_content,
    pack_content as local_pack_content,
    append_local_session_event,
    promote_worktree as local_promote_worktree,
    prune_stale_worktrees as local_prune_stale_worktrees,
    preview_worktree_rebase as local_preview_worktree_rebase,
    rebase_worktree as local_rebase_worktree,
    recreate_worktree as local_recreate_worktree,
    restore_owned_head as local_restore_owned_head,
    replay_change as local_replay_change,
    replay_snapshot as local_replay_snapshot,
    ref_history as local_ref_history,
    repo_status,
    remove_worktrees as local_remove_worktrees,
    remove_worktree as local_remove_worktree,
    revert_change as local_revert_change,
    revert_snapshot as local_revert_snapshot,
    restore_workspace as local_restore_workspace,
    restore_workspace_paths as local_restore_workspace_paths,
    drop_stash,
    switch_line,
    sync_all_worktrees as local_sync_all_worktrees,
    sync_worktree as local_sync_worktree,
    get_local_session,
    land_local_change,
    apply_stash,
    resume_local_session,
    worktree_doctor as local_worktree_doctor,
    workspace_status as local_workspace_status,
    get_local_plan_revision,
)


from .app_surfaces import (
    TASK_TRACKING_MODES,
    _ctx,
    _review_action,
    app,
    attest_app,
    auth_app,
    benchmark_app,
    change_app,
    config_app,
    doctor_app,
    gc_app,
    land_app,
    line_app,
    patchset_app,
    plan_app,
    plan_session_app,
    policy_app,
    queue_app,
    ref_app,
    register_cli_subapps,
    release_app,
    remote_app,
    repo_app,
    review_app,
    session_app,
    stash_app,
    snapshot_app,
    stack_app,
    task_app,
    workflow_app,
    workspace_app,
    worktree_app,
)

_export_from_module(globals(), _task_dag_app_exports)
del _task_dag_app_exports
del _export_from_module

register_cli_subapps()
register_install_command(app)
register_init_command(app)


from .commands.bootstrap import bootstrap_cli_commands

bootstrap_cli_commands(sys.argv[1:])
if (package_module := sys.modules.get(__package__)) is not None:
    package_module.app = app

if __name__ == "__main__":
    app()
