//! Rust foundation for the public `ait-agent` manager and configuration-backed
//! native agent workers.
//!
//! This crate intentionally starts with transport-neutral runtime planning and
//! event-loop ownership. Transport protocol loops move behind these modules in
//! later slices.

pub mod cli;
pub mod event_loop;
pub mod file_store;
mod json_support;
pub mod language_bindings;
pub mod management;
pub mod manifest;
pub mod platform;
pub mod runtime;
pub mod supervisor;
pub mod transport;
pub mod transport_config;
pub mod web_runtime;

pub use cli::{
    plan_agent_cli_launch, plan_agent_cli_launch_json, AgentCliLaunchPlan, AgentCliPlanInput,
    AgentWorkerCommandPlan, AgentWorkerLaunchState,
};
pub use event_loop::{
    agent_discord_gateway_runtime_plan_json, agent_discord_ingress_runtime_plan_json,
    agent_discord_interaction_job_execute_json, agent_discord_reply_delivery_callback_plan_json,
    agent_discord_reply_delivery_execution_plan_json, agent_discord_rest_delivery_execute_json,
    agent_event_loop_reactor_plan_json, agent_line_event_job_execute_json,
    agent_line_http_transaction_execute_json, agent_line_reply_delivery_execute_json,
    agent_line_webhook_ingress_plan_json, agent_runtime_admission_plan_json,
    agent_slack_background_reply_transaction_execute_json,
    agent_slack_command_http_ingress_plan_json, agent_slack_command_http_transaction_plan_json,
    agent_slack_command_job_execute_json, agent_slack_ingress_runtime_plan_json,
    agent_slack_reply_delivery_plan_json, agent_slack_response_url_delivery_execute_json,
    agent_slack_socket_mode_runtime_plan_json, agent_slack_socket_mode_transaction_plan_json,
    agent_telegram_api_execute, agent_telegram_api_json_execute_json,
    agent_telegram_api_method_execution_plan_json, agent_telegram_background_sync_state_plan_json,
    agent_telegram_callback_action_boundary_plan_json, agent_telegram_callback_execution_plan_json,
    agent_telegram_callback_side_effect_adapter_plan_json,
    agent_telegram_command_runtime_plan_json,
    agent_telegram_command_trigger_execute_operation_json,
    agent_telegram_command_trigger_execution_plan_json, agent_telegram_dispatch_runtime_plan_json,
    agent_telegram_event_trigger_plan_json, agent_telegram_file_download_execute,
    agent_telegram_file_download_execution_plan_json,
    agent_telegram_live_reply_delivery_callback_plan_json,
    agent_telegram_logical_turn_runtime_plan_json, agent_telegram_message_delivery_execute_json,
    agent_telegram_message_formatting_plan_json,
    agent_telegram_operational_trigger_callback_plan_json,
    agent_telegram_owner_bootstrap_plan_json, agent_telegram_polling_cycle_plan_json,
    agent_telegram_reply_delivery_execute_json, agent_telegram_reply_delivery_execution_plan_json,
    agent_telegram_reply_spool_execution_plan_json,
    agent_telegram_reply_turn_delivery_callback_plan_json,
    agent_telegram_service_runtime_shell_plan_json,
    agent_telegram_service_shell_callback_plan_json, agent_telegram_submission_runtime_plan_json,
    agent_telegram_turn_input_plan_json, agent_telegram_update_batch_dispatch_plan_json,
    agent_telegram_update_dispatch_plan_json, agent_telegram_webhook_ingress_plan_json,
    agent_telegram_workflow_notification_format_json, agent_telegram_workflow_query_plan_json,
    agent_websocket_event_loop_turn_plan_json, agent_websocket_registration_action_plan_json,
    agent_websocket_runtime_orchestration_plan_json,
    agent_websocket_runtime_timer_scheduler_plan_json, agent_websocket_shard_event_batch_plan_json,
    execute_agent_websocket_lifecycle_actions, execute_agent_websocket_reactor_run,
    execute_agent_websocket_reactor_tick, execute_agent_websocket_registration_actions,
    execute_with_discord_interaction_job_ports, execute_with_discord_rest_delivery_executor,
    execute_with_line_event_job_ports, execute_with_line_http_transaction_ports,
    execute_with_line_reply_delivery_executor, execute_with_slack_background_reply_transaction,
    execute_with_slack_command_job_ports, execute_with_slack_response_url_delivery_executor,
    execute_with_telegram_api_json_ports, execute_with_telegram_api_transport_ports,
    execute_with_telegram_background_sync_ports, execute_with_telegram_command_runtime_ports,
    execute_with_telegram_command_trigger_operation_executor,
    execute_with_telegram_file_download_ports, execute_with_telegram_message_delivery_ports,
    execute_with_telegram_operational_trigger_ports, execute_with_telegram_owner_bootstrap_ports,
    execute_with_telegram_reply_delivery_ports, execute_with_telegram_reply_spool_ports,
    execute_with_telegram_service_cycle_ports, execute_with_telegram_service_run_ports,
    execute_with_telegram_update_lifecycle_runtime,
    execute_with_telegram_webhook_transaction_ports,
    execute_with_telegram_workflow_notification_ports, execute_with_websocket_lifecycle_executor,
    format_with_telegram_workflow_notification_formatter, load_telegram_reply_spool_entries,
    plan_agent_event_loop_reactor, plan_agent_runtime_admission,
    plan_with_discord_gateway_runtime_planner, plan_with_discord_ingress_runtime_planner,
    plan_with_line_webhook_ingress_planner, plan_with_slack_command_http_ingress_planner,
    plan_with_slack_command_http_transaction_planner, plan_with_slack_ingress_runtime_planner,
    plan_with_slack_reply_delivery_planner, plan_with_slack_socket_mode_runtime_planner,
    plan_with_slack_socket_mode_transaction_planner, plan_with_telegram_api_method_planner,
    plan_with_telegram_background_sync_state_planner, plan_with_telegram_command_runtime_planner,
    plan_with_telegram_dispatch_runtime_planner, plan_with_telegram_event_trigger_planner,
    plan_with_telegram_file_download_planner, plan_with_telegram_logical_turn_runtime_planner,
    plan_with_telegram_message_formatting_planner, plan_with_telegram_owner_bootstrap_planner,
    plan_with_telegram_reply_spool_planner, plan_with_telegram_submission_runtime_planner,
    plan_with_telegram_turn_input_planner, plan_with_telegram_webhook_ingress_planner,
    plan_with_telegram_workflow_query_planner, plan_with_websocket_runtime_orchestration_planner,
    plan_with_websocket_runtime_timer_scheduler, register_agent_event_loop_read_write, AgentEvent,
    AgentEventLoop, AgentEventLoopBackend, AgentEventLoopBackendPort, AgentEventLoopConfig,
    AgentEventLoopDriver, AgentEventLoopPollPort, AgentEventLoopReadWriteRegistrationPort,
    AgentEventLoopReadableRegistrationPort, AgentEventLoopRegistrationPort,
    AgentEventLoopUnregistrationPort, AgentReactorPlan, AgentReactorPlanInput,
    AgentReactorShardPlan, AgentReactorWorkerSlot, AgentRuntimeAdmissionInput,
    AgentRuntimeAdmissionPlan, AgentRuntimeCapacity, AgentRuntimeShardAdmission,
    AgentRuntimeWorkerLease, DefaultDiscordGatewayRuntimePlanner,
    DefaultDiscordIngressRuntimePlanner, DefaultDiscordInteractionJobBackendPort,
    DefaultDiscordInteractionJobStatePort, DefaultDiscordRestDeliveryExecutor,
    DefaultLineEventJobBackendPort, DefaultLineEventJobDeliveryPort, DefaultLineEventJobStatePort,
    DefaultLineHttpTransactionEventJobPort, DefaultLineHttpTransactionIngressPort,
    DefaultLineReplyDeliveryExecutor, DefaultLineWebhookIngressPlanner,
    DefaultSlackCommandHttpTransactionPlanner, DefaultSlackCommandJobBackendPort,
    DefaultSlackCommandJobDeliveryPort, DefaultSlackCommandJobStatePort,
    DefaultSlackIngressRuntimePlanner, DefaultSlackReplyDeliveryPlanner,
    DefaultSlackResponseUrlDeliveryExecutor, DefaultSlackSocketModeRuntimePlanner,
    DefaultSlackSocketModeTransactionPlanner, DefaultTelegramApiMethodPlanner,
    DefaultTelegramBackgroundSyncStatePlanner, DefaultTelegramCommandRuntimePlanner,
    DefaultTelegramCommandTriggerOperationExecutor, DefaultTelegramDispatchRuntimePlanner,
    DefaultTelegramEventTriggerPlanner, DefaultTelegramFileDownloadPlanner,
    DefaultTelegramLogicalTurnRuntimePlanner, DefaultTelegramMessageFormattingPlanner,
    DefaultTelegramOperationalTriggerCallbackPlanner, DefaultTelegramOwnerBootstrapPlanner,
    DefaultTelegramReplyDeliveryPlanner, DefaultTelegramReplySpoolPlanner,
    DefaultTelegramServiceCycleStatePort, DefaultTelegramSubmissionRuntimePlanner,
    DefaultTelegramTurnInputPlanner, DefaultTelegramUpdateAssistantReplyExecutor,
    DefaultTelegramUpdateFileDownloadExecutor, DefaultTelegramUpdateLifecycleExecutor,
    DefaultTelegramUpdateMessageExecutor, DefaultTelegramWebhookIngressPlanner,
    DefaultTelegramWebhookTransactionIngressPort, DefaultTelegramWorkflowNotificationFormatter,
    DefaultTelegramWorkflowQueryPlanner, DefaultWebSocketLifecycleExecutor,
    DefaultWebSocketRuntimeOrchestrationPlanner, DefaultWebSocketRuntimeTimerScheduler,
    DiscordGatewayRuntimePlanner, DiscordIngressRuntimePlanner, DiscordInteractionJobBackendPort,
    DiscordInteractionJobStatePort, DiscordRestDeliveryExecutor,
    ExternalProgramTelegramSttExecutor, LineEventJobBackendPort, LineEventJobDeliveryPort,
    LineEventJobStatePort, LineHttpTransactionEventJobPort, LineHttpTransactionIngressPort,
    LineReplyDeliveryExecutor, LineWebhookIngressPlanner, MonotonicTelegramLogicalTurnClock,
    NativeTelegramApiJsonHttpExecutor, NativeTelegramApiTransportExecutor,
    NativeTelegramBackgroundSyncChildExecutionPort, NativeTelegramBackgroundSyncOperationPort,
    NativeTelegramBackgroundSyncServicePort, NativeTelegramEventTriggerRegistryLoader,
    NativeTelegramFileDownloadApiPort, NativeTelegramFileDownloadStorePort,
    NativeTelegramMessageDeliveryApiPort, NativeTelegramOperationalTriggerDeliveryPort,
    NativeTelegramReplyDeliveryPort, NativeTelegramUpdateBootstrapPort,
    NativeTelegramUpdateCommandPort, NativeTelegramUpdateCommandRuntimeExecutor,
    NativeTelegramUpdateInputPort, NativeTelegramUpdateLifecyclePort,
    NativeTelegramUpdateLifecycleRuntime, NativeTelegramUpdateMessagePort,
    NativeTelegramUpdateOperationalExecutor, NativeTelegramUpdateOperationalPort,
    NativeTelegramUpdateOwnerBootstrapExecutor, NativeTelegramWorkflowNotificationMessagePort,
    RuntimeBindingTelegramBackgroundSyncReadPort, RuntimeBindingTelegramCommandRuntimeStatePort,
    RuntimeBindingTelegramOperationalTriggerStatePort,
    RuntimeBindingTelegramOwnerBootstrapStatePort, RuntimeBindingTelegramReplySpoolStatePort,
    SelectedBackendTelegramCommandRuntimeReadPort, SlackCommandHttpIngressPlanner,
    SlackCommandHttpTransactionPlanner, SlackCommandJobBackendPort, SlackCommandJobDeliveryPort,
    SlackCommandJobStatePort, SlackIngressRuntimePlanner, SlackReplyDeliveryPlanner,
    SlackResponseUrlDeliveryExecutor, SlackSocketModeRuntimePlanner,
    SlackSocketModeTransactionPlanner, SystemTelegramBackgroundSyncClockPort,
    SystemTelegramCommandRuntimeClockPort, SystemTelegramOperationalTriggerDiagnosticsPort,
    SystemTelegramOwnerBootstrapClockPort, SystemTelegramReplySpoolClockPort,
    SystemTelegramUpdateDiagnosticsPort, TelegramApiJsonHttpExecutor, TelegramApiMethodPlanner,
    TelegramApiRetrySleeper, TelegramApiTransportExecution, TelegramApiTransportExecutor,
    TelegramBackgroundSyncBindingReadPort, TelegramBackgroundSyncChildExecutionPort,
    TelegramBackgroundSyncClockPort, TelegramBackgroundSyncExecution,
    TelegramBackgroundSyncExecutionError, TelegramBackgroundSyncExecutionErrorKind,
    TelegramBackgroundSyncOperationPort, TelegramBackgroundSyncStatePlanner,
    TelegramBackgroundSyncSubmissionPort, TelegramCommandRuntimeClockPort,
    TelegramCommandRuntimeDeliveryPort, TelegramCommandRuntimeExecutionError,
    TelegramCommandRuntimeExecutionErrorKind, TelegramCommandRuntimePlanner,
    TelegramCommandRuntimeReadPort, TelegramCommandRuntimeStatePort,
    TelegramCommandTriggerOperationExecutor, TelegramDispatchRuntimePlanner,
    TelegramEventTriggerPlanner, TelegramFileCacheState, TelegramFileDownloadApiExecution,
    TelegramFileDownloadApiPort, TelegramFileDownloadExecution, TelegramFileDownloadExecutionError,
    TelegramFileDownloadExecutionErrorKind, TelegramFileDownloadPlanner,
    TelegramFileDownloadStorePort, TelegramKeyedDispatchError, TelegramKeyedDispatchErrorKind,
    TelegramKeyedDispatchFuture, TelegramKeyedDispatchJobExecutor, TelegramKeyedDispatchRuntime,
    TelegramLogicalTurn, TelegramLogicalTurnBufferOutcome, TelegramLogicalTurnClockPort,
    TelegramLogicalTurnError, TelegramLogicalTurnErrorKind, TelegramLogicalTurnRuntime,
    TelegramLogicalTurnRuntimePlanner, TelegramLogicalTurnSleepPort, TelegramLogicalTurnStep,
    TelegramMessageDeliveryApiPort, TelegramMessageFormattingPlanner,
    TelegramOperationalTriggerCallbackPlanner, TelegramOperationalTriggerDeliveryPort,
    TelegramOperationalTriggerDiagnosticsPort, TelegramOperationalTriggerExecutionConfig,
    TelegramOperationalTriggerExecutionError, TelegramOperationalTriggerExecutionErrorKind,
    TelegramOperationalTriggerPorts, TelegramOperationalTriggerStatePort,
    TelegramOwnerBootstrapClockPort, TelegramOwnerBootstrapExecutionError,
    TelegramOwnerBootstrapExecutionErrorKind, TelegramOwnerBootstrapMessagePort,
    TelegramOwnerBootstrapPlanner, TelegramOwnerBootstrapStatePort, TelegramPreparedUpdateInput,
    TelegramReplyDeliveryExecutionError, TelegramReplyDeliveryExecutionErrorKind,
    TelegramReplyDeliveryOperationKind, TelegramReplyDeliveryPlanner, TelegramReplyDeliveryPort,
    TelegramReplySpoolClockPort, TelegramReplySpoolEntries, TelegramReplySpoolExecutionError,
    TelegramReplySpoolExecutionErrorKind, TelegramReplySpoolMutation, TelegramReplySpoolPlanner,
    TelegramReplySpoolStatePort, TelegramServiceCycleBackgroundSyncPort,
    TelegramServiceCycleDispatchPort, TelegramServiceCyclePollPort, TelegramServiceCycleStatePort,
    TelegramServiceRunClockPort, TelegramServiceRunCycleExecutor, TelegramServiceRunCyclePort,
    TelegramServiceRunSleepPort, TelegramServiceRunStopPort, TelegramSttExecutionError,
    TelegramSttExecutionErrorKind, TelegramSttExecutor, TelegramSubmissionDispatchPort,
    TelegramSubmissionExecutionError, TelegramSubmissionExecutionErrorKind,
    TelegramSubmissionExecutionPort, TelegramSubmissionFuture, TelegramSubmissionRuntime,
    TelegramSubmissionRuntimePlanner, TelegramTurnInputPlanner,
    TelegramUpdateAssistantReplyExecutor, TelegramUpdateBootstrapPort,
    TelegramUpdateBootstrapRequest, TelegramUpdateCommandExecutor, TelegramUpdateCommandPort,
    TelegramUpdateCommandRequest, TelegramUpdateDeliveryPort, TelegramUpdateDiagnosticsPort,
    TelegramUpdateFileDownloadExecutor, TelegramUpdateInputError, TelegramUpdateInputErrorKind,
    TelegramUpdateInputMode, TelegramUpdateInputPort, TelegramUpdateInputRequest,
    TelegramUpdateJob, TelegramUpdateJobConfig, TelegramUpdateJobError, TelegramUpdateJobErrorKind,
    TelegramUpdateJobPorts, TelegramUpdateLifecycleExecutor, TelegramUpdateLifecyclePort,
    TelegramUpdateLifecycleRuntimePort, TelegramUpdateMessageExecutor,
    TelegramUpdateNormalTurnRequest, TelegramUpdateOperationalExecutor,
    TelegramUpdateOperationalMessagePort, TelegramUpdateOperationalPort,
    TelegramUpdateOperationalRequest, TelegramUpdateOwnerBootstrapExecutor,
    TelegramUpdatePortError, TelegramWebhookIngressPlanner, TelegramWebhookTransactionDispatchPort,
    TelegramWebhookTransactionIngressPort, TelegramWorkflowNotificationExecution,
    TelegramWorkflowNotificationExecutionError, TelegramWorkflowNotificationExecutionErrorKind,
    TelegramWorkflowNotificationFormatter, TelegramWorkflowNotificationMessagePort,
    TelegramWorkflowQueryPlanner, ThreadTelegramApiRetrySleeper, ThreadTelegramLogicalTurnSleeper,
    WebSocketLifecycleExecutor, WebSocketRuntimeOrchestrationPlanner,
    WebSocketRuntimeTimerScheduler, TELEGRAM_STT_EXECUTION_CONTRACT, TELEGRAM_STT_REQUEST_CONTRACT,
    TELEGRAM_STT_RESPONSE_CONTRACT,
};
pub use file_store::{
    agent_file_store_execute_json, agent_file_store_execute_with_store,
    agent_file_store_read_bytes_json, agent_file_store_read_bytes_with_store,
    AGENT_FILE_STORE_CONTRACT,
};
pub use language_bindings::{
    agent_management_binding_json, language_binding_info_json, LANGUAGE_BINDING_CONTRACT,
};
pub use management::{
    parse_capability_report, AgentManagementRuntime, AgentSupervisorAction,
    AgentWorkerCapabilityProbe, AgentWorkerCapabilityReport, NativeAgentWorkerCapabilityProbe,
    AGENT_WORKER_CAPABILITY_CONTRACT,
};
pub use manifest::{
    agent_default_worker_manifest_config_json, agent_list_manifest_workers_json,
    agent_normalize_worker_manifest_document_json, agent_select_telegram_worker_json,
    agent_upsert_worker_manifest_worker_json, agent_worker_manifest_ir_version,
    agent_worker_manifest_schema_json, agent_worker_manifest_store_execute_json,
    count_manifest_workers, list_manifest_workers, normalize_agent_worker_manifest,
    AgentWorkerCount, AgentWorkerSpec, AGENT_WORKER_MANIFEST_STORE_CONTRACT,
};
pub use platform::{
    close_native_socket, native_socket_from_i64, native_socket_from_u64, native_socket_is_valid,
    native_socket_take_error, native_socket_to_u64, set_native_socket_close_on_exec,
    set_native_socket_nonblocking, shutdown_native_socket, tcp_listener_native_socket,
    tcp_stream_into_native_socket, tcp_stream_native_socket, NativeSocket, INVALID_NATIVE_SOCKET,
};
pub use runtime::{
    agent_default_runtime_binding_state_payload_json, agent_gateway_reply_runtime_execute_json,
    agent_normalize_runtime_binding_state_document_json, agent_remote_runtime_backend_execute_json,
    agent_runtime_backend_execute_json, agent_runtime_binding_projection_json,
    agent_runtime_binding_state_ir_version, agent_runtime_binding_state_schema_json,
    agent_runtime_binding_store_execute_json, configure_agent_local_reply_process_defaults,
    execute_with_agent_gateway_reply_provider, plan_agent_runtime, AgentLocalReplyProcessConfig,
    AgentLocalReplyProcessDefaults, AgentLocalReplyProvider, AgentLocalReplyProviderError,
    AgentLocalReplyRuntimeSettings, AgentLocalRuntimeBackend, AgentRuntimeBackend,
    AgentRuntimeBindingStore, AgentRuntimeHttpExecutor, AgentRuntimePlan, AgentRuntimePlanInput,
    AgentRuntimeRetrySleeper, ExternalProcessAgentLocalReplyProvider,
    NativeAgentLocalRuntimeBackend, NativeAgentRuntimeHttpExecutor, RemoteAitRuntimeBackend,
    SelectedAitRuntimeBackend, ThreadAgentRuntimeRetrySleeper,
    AGENT_GATEWAY_CODEX_THREAD_BINDING_CONTRACT, AGENT_GATEWAY_REPLY_PROVIDER_REQUEST_CONTRACT,
    AGENT_GATEWAY_REPLY_PROVIDER_RESPONSE_CONTRACT, AGENT_GATEWAY_REPLY_RUNTIME_CONTRACT,
    AGENT_GATEWAY_TURN_TELEMETRY_CONTRACT, AGENT_REMOTE_RUNTIME_BACKEND_CONTRACT,
    AGENT_RUNTIME_BACKEND_CONTRACT, AGENT_RUNTIME_BINDING_STORE_CONTRACT,
};
pub use supervisor::{
    agent_supervisor_public_worker_payload_json, consume_worker_termination_context_json,
    inspect_worker_process_status, inspect_worker_process_status_json, plan_worker_launches,
    plan_worker_supervisor_lifecycle, plan_worker_supervisor_lifecycle_json, read_worker_log_tail,
    read_worker_log_tail_json, start_worker_process, start_worker_process_json,
    stop_worker_process, stop_worker_process_json, AgentWorkerLifecycleOperation,
    AgentWorkerLifecyclePlan, AgentWorkerLifecyclePlanInput, AgentWorkerLifecycleSpec,
    AgentWorkerLogTail, AgentWorkerLogTailInput, AgentWorkerPidFileInspection,
    AgentWorkerProcessPaths, AgentWorkerProcessStatus, AgentWorkerProcessStatusInput,
    AgentWorkerRuntimeHealth, AgentWorkerRuntimePaths as AgentSupervisorWorkerRuntimePaths,
    AgentWorkerStartInput, AgentWorkerStartResult, AgentWorkerStartSpec, AgentWorkerStopInput,
    AgentWorkerStopResult, WorkerLaunchPlan, AGENT_SUPERVISOR_TERMINATION_CONTEXT_CONTRACT,
};
pub use transport::{
    agent_compact_transport_event_envelope_json, agent_compact_transport_reply_envelope_json,
    agent_transport_binding_metadata_json, agent_transport_config_clean_optional_text,
    agent_transport_config_normalize_base_url, agent_transport_config_parse_int,
    agent_transport_config_parse_timeout_seconds, agent_transport_config_split_message_chunks,
    agent_transport_config_split_message_chunks_json, agent_transport_envelope_ir_version,
    agent_transport_envelope_schema_json, agent_transport_event_envelope_json,
    agent_transport_http_execute_bytes_request, agent_transport_http_execute_json_request_json,
    agent_transport_http_execute_multipart_json_request_json,
    agent_transport_http_execute_multipart_json_request_with_bytes,
    agent_transport_reply_envelope_json, agent_transport_retry_default_errnos_json,
    agent_transport_retry_default_markers_json,
    agent_transport_retry_default_server_read_markers_json, agent_transport_retry_delay_seconds,
    agent_transport_retry_is_loopback_url,
    agent_transport_retry_is_retryable_server_read_error_json,
    agent_transport_retry_is_retryable_transport_error_json, agent_transport_retry_timeout_phrase,
    agent_transport_retry_timeout_value, agent_transport_websocket_connect_execute_json,
    agent_transport_websocket_fd_io_execute_json, agent_transport_websocket_frame_plan_json,
    agent_transport_websocket_handshake_plan_json, agent_transport_websocket_stream_plan_json,
    agent_transport_websocket_tls_execute_json, AgentTransportConfigIntMode,
    AgentTransportHttpBytesExecution, TransportKind,
};
pub use transport_config::{
    agent_env_file_load_json, agent_repo_default_model_load_json, parse_agent_env_file,
    resolve_agent_worker_config, AgentRuntimeMode, AgentRuntimeTarget, AgentSecret,
    AgentSharedWorkerConfig, AgentWorkerConfigInput, AgentWorkerRuntimeConfig,
    AgentWorkerRuntimePaths, AgentWorkflowMode, DiscordWorkerConfig, LineWorkerConfig,
    SlackWorkerConfig, TelegramSttMode, TelegramWorkerConfig, TelegramWorkerMode,
    AGENT_ENV_FILE_LOAD_CONTRACT, AGENT_REPO_DEFAULT_MODEL_LOAD_CONTRACT,
};
pub use web_runtime::{agent_web_runtime_execute_json, AGENT_WEB_RUNTIME_CONTRACT};
